### ISSUE TITLE
Dark mode not working.

### ISSUE THREAD

**Issue by yogurttoad** [mukul500/AnimeXStream#1]
I'm using the app on a Samsung Galaxy S8. I have "Night Mode" selected under my display settings. The app still has the classic white background. With no way to force dark mode in the app, I can't access this feature.

**Comment by mukul500** [comment]
Can you please try it with power saving mode

**Comment by yogurttoad** [comment]
It does indeed work on power saving mode.

**Comment by mukul500** [comment]
Currently its integrated with system. But in future it will have seperate button to turn it on or off

**Comment by MichJB93** [comment]
> Currently its integrated with system. But in future it will have seperate button to turn it on or off

Thanks! this is the same issues I'm having right now, good to know that it will be fixed soon
