### ISSUE TITLE
Servers are not good

### ISSUE THREAD

**Issue by Echo2124** [mukul500/AnimeXStream#10]
Is there any chance that you could scrape from a site that uses Google video to host their anime as they use a CDN which means that buffering isn't as much of an issue for people that do not live near the server that the video is hosted on. I have a decent internet connection that does 100mbps down and 40mbps up. I am experiencing pretty bad buffering in the app at the moment which probably as something to do with the servers that are being in use at the moment. Other than that great job on the app, I am looking forward to seeing how it'll improve in the future.

**Comment by mukul500** [comment]
Try version 0.2.0 google video server support added

**Comment by Echo2124** [comment]
> d

Works much better, thanks for implementing that. I can use video without problems. Thanks for your work, it works amazing.

**Comment by robinransommmmm** [comment]
can you add a recently viewed feature?
