### ISSUE TITLE
Server issue

### ISSUE THREAD

**Issue by emsufy** [mukul500/AnimeXStream#100]
Hi there, like many others I've seen posted I am having the server issue and cannot watch any shows. Please advise

**Comment by zeeshanhussain** [comment]
Use https://transfer.sh/bh9ob/AnimexStream-v0.2.1-arm64-v8a-release.apk until its fixed in the current repo.

**Comment by mukul500** [comment]
Check new Release [Download v0.2.3](https://github.com/mukul500/AnimeXStream/releases/tag/v0.2.3)
