### ISSUE TITLE
Server Error

### ISSUE THREAD

**Issue by Arbaazyaseen15** [mukul500/AnimeXStream#101]
I'm having server error on every next episode of a series.

**Comment by zeeshanhussain** [comment]
Use https://transfer.sh/bh9ob/AnimexStream-v0.2.1-arm64-v8a-release.apk until its fixed in the current repo.

**Comment by frytkisasmaczne** [comment]
who the hell opens issues when there are already issues about the same error. a bit of culture would be nice, it's not like this is a project by some big company with offices of people hired specifically for dealing with your inability to read

**Comment by GoluLiliput** [comment]
Shut up

**Comment by mukul500** [comment]
Check new Release [Download v0.2.3](https://github.com/mukul500/AnimeXStream/releases/tag/v0.2.3)

**Comment by mukul500** [comment]
> Use https://transfer.sh/bh9ob/AnimexStream-v0.2.1-arm64-v8a-release.apk until its fixed in the current repo.

Don't use this Apk it will remove all of your favorites and episode tracking
