### ISSUE TITLE
Server error

### ISSUE THREAD

**Issue by CAESAR5769** [mukul500/AnimeXStream#102]
Im having a server error on every episode plzz help
![Screenshot_2020-08-17-16-21-55-042_net xblacky animexstream](https://user-images.githubusercontent.com/69796155/90389064-7cba5280-e0a6-11ea-9093-43253c6f6f90.jpg)

**Comment by zeeshanhussain** [comment]
Use https://transfer.sh/bh9ob/AnimexStream-v0.2.1-arm64-v8a-release.apk until its fixed in the current repo.

**Comment by veisz** [comment]
Not to rush you or anything, but when will it be done? About a week or so? Not to demand or anything, just asking.

**Comment by zeeshanhussain** [comment]
> Not to rush you or anything, but when will it be done? About a week or so? Not to demand or anything, just asking.

When @mukul500 will be free to review and merge.
