### ISSUE TITLE
Help my anime x stream is not working 

### ISSUE THREAD

**Issue by Riyavmehta** [mukul500/AnimeXStream#104]
![Screenshot_20200818-012046_Anime X Stream](https://user-images.githubusercontent.com/69362450/90438076-17d81a00-e0f1-11ea-90b1-30632db1ee3f.jpg)

**Comment by mukul500** [comment]
Check new Release [Downlaod V0.2.3](https://github.com/mukul500/AnimeXStream/releases/tag/v0.2.3)

**Comment by mukul500** [comment]
Check new Release [Download V0.2.3](https://github.com/mukul500/AnimeXStream/releases/tag/v0.2.3)
