### ISSUE TITLE
Server Error...

### ISSUE THREAD

**Issue by Retaku** [mukul500/AnimeXStream#106]
I am unable to watch most anime like Boku no hero, Black Clover, Naruto, and etc I ask for you to fix when you can or tell me how I can fix the problem myself please and thank you....

**Comment by SGSTAR01** [comment]
Download the 0.2.1 version of this app

**Comment by mukul500** [comment]
Check new Release [Downlaod V0.2.3](https://github.com/mukul500/AnimeXStream/releases/tag/v0.2.3)
