### ISSUE TITLE
Apk can't install 

### ISSUE THREAD

**Issue by Dewet-sa** [mukul500/AnimeXStream#108]
All the updates can't install

**Comment by mukul500** [comment]
I think you have installed any unsigned apk provided on forum by Google drive link. These apk are by our contributor that is not signed by official keys. I always suggest you not to install any apk aside from our release page. So you need to uninstall previous apk and than install latest release. This will result you loss your Favourite animes, episode progress. So remeber always use our release page for official apk. Not build by others.

**Comment by jamilxt** [comment]
> All the updates can't install

Uninstall the previous version of the app. And, try fresh installing. ^_^

@mukul500  Thank you for fixing the issue. ^_^ 
I was planning to debug it yesterday to practice. Such an amazing app you've built. Thanks again.
