### ISSUE TITLE
make this for windows 

### ISSUE THREAD

**Issue by kunal4896** [mukul500/AnimeXStream#12]
im new in coding if i knew little bit main bna leta khud se hi

**Comment by DoggoOfSpeed** [comment]
That most likely won't happend. This app was made in Kotlin and it would have to be remade from the ground to work on any other platform. Not only that, the creator would (most likely) have to learn a new programming language and that takes pressious time.

**Comment by shoukolate** [comment]
@kunal4896 For windows you can try Kaw Anime
