### ISSUE TITLE
Can't play any video and the search option are not working and if i open any anime it shows nothing. 

### ISSUE THREAD

**Issue by anindya127** [mukul500/AnimeXStream#124]
![Screenshot_2020-08-28-00-22-31-627_net xblacky animexstream](https://user-images.githubusercontent.com/70308564/91498537-bdee0600-e8e1-11ea-8e55-96fd51e02879.jpg)
![Screenshot_2020-08-28-00-22-24-505_net xblacky animexstream](https://user-images.githubusercontent.com/70308564/91498548-c1818d00-e8e1-11ea-98c3-d1ad4fe67689.jpg)
And i am currently using the latest version of anime x stream.

**Comment by vinaydwivedi01** [comment]
which version are you using ?

**Comment by anindya127** [comment]
0.2.3

**Comment by vinaydwivedi01** [comment]
> 0.2.3
> Is it working for you?

Yes it is

**Comment by anindya127** [comment]
What is your android version?
And country?

**Comment by anindya127** [comment]
Thanks for the update 0.2.4. Now all of my problems are fixed
