### ISSUE TITLE
Is it because of the android version?

### ISSUE THREAD

**Issue by CMAB03** [mukul500/AnimeXStream#127]
This is really weird. I have this friend of mine who has lower android version than mine and her app works really fine, but my android 10 phone has this weird error. I don't know if other android 10 phones have the same issue like mine. I know this is not my place to say this, but please urgently fix it. Thank you if you are gonna read this, though.

**Comment by anindya127** [comment]
I don't think that is the case . When i 1st download the update it was working fine. But the next day it start showing something is wrong. If it is for the android version then it should be showing that massage after i install the app.

**Comment by CMAB03** [comment]
Same here, too. I downloaded it and it was fine for like 1-3 days then after that, it stopped working.

**Comment by CMAB03** [comment]
I am really grateful that you fixed it now. I wish  you good luck and keep safe from the virus right now. :)
