### ISSUE TITLE
New episodes are blank  they play after 15-30 mins

### ISSUE THREAD

**Issue by Sdark19** [mukul500/AnimeXStream#129]
![Screenshot_2020-09-01-00-22-20-589_net xblacky animexstream](https://user-images.githubusercontent.com/68708731/91755746-4245cf00-ebe9-11ea-9239-713e7bcd7b6c.jpg)

**Comment by mukul500** [comment]
Maybe they uplaod late to that server, I am using to fetch media

**Comment by Sdark19** [comment]
Now it's not even loading after 3 hrs
