### ISSUE TITLE
Server error

### ISSUE THREAD

**Issue by shadow-prince** [mukul500/AnimeXStream#133]
> The latest [**_version_**](https://github.com/mukul500/AnimeXStream/releases/tag/v0.2.4) was good but again `Server problem!` occured like this [**_version_**](https://github.com/mukul500/AnimeXStream/releases/tag/v0.2.3)

**Comment by Faizar123** [comment]
![Screenshot_20200910-154526.png](https://user-images.githubusercontent.com/70917974/92713613-034c1200-f37d-11ea-9941-bd2110dddae3.png)

Plz fix it

**Comment by GoluLiliput** [comment]
Try AnimeZone app here...
https://discord.gg/CvGFx2h

**Comment by mukul500** [comment]
@GoluLiliput & @Faizar123 Stop Promoting apps here.

**Comment by Faizar123** [comment]
> @GoluLiliput & @Faizar123 Stop Promoting apps here.

Sir i am not promote any apps...
I love anime x stream...
And i need this app for watching anime
