### ISSUE TITLE
Server error

### ISSUE THREAD

**Issue by Virus00728** [mukul500/AnimeXStream#135]
![Screenshot_2020-09-12-00-45-09-50_7e119e2a6a7c824e2d747bede4ec673e](https://user-images.githubusercontent.com/71149784/92961571-45667800-f491-11ea-9c82-3bf66fc3f9fe.jpg)
it keeps saying server error, can't watch anything

**Comment by mukul500** [comment]
Open App ->Wait 1 Minute - > Force Close app - > Do this 2 times. It Will Work. If it doesn't work 
Mention your Country, City, Device, Android Version. I will Look at it.

**Comment by Virus00728** [comment]
Oh shit, I forgot to close the issue even after the problem was solved. I
am sorry if that caused you any trouble
