### ISSUE TITLE
SERVER ERROR

### ISSUE THREAD

**Issue by Einiv** [mukul500/AnimeXStream#141]
It's been how many days since this bug started, when will you fix this problem?

**Comment by mukul500** [comment]
Open App ->Wait 1 Minute - > Force Close app - > Do this 2 times. It Will Work. If it doesn't work 
Mention your Country, City, Device, Android Version. I will Look at it.

**Comment by Faizar123** [comment]
> It's been how many days since this bug started, when will you fix this problem?

 Mine is worked perfectly
I am from Bangladesh

**Comment by Einiv** [comment]
> Open App ->Wait 1 Minute - > Force Close app - > Do this 2 times. It Will Work. If it doesn't work
> Mention your Country, City, Device, Android Version. I will Look at it.


OMG THANK YOU VERY MUCH, I DIDN'T TO ACTUALLY WORK
