### ISSUE TITLE
Whenever I click an anime the screen Goes black

### ISSUE THREAD

**Issue by armed1234** [mukul500/AnimeXStream#151]
i cant watch anything cuz episodes  dont load the screen goes black

**Comment by ckonar92** [comment]
Same here

**Comment by Hawk768** [comment]
It's happen with me I tried in arm64-v8a is it the same version you use and any solution

**Comment by armed1234** [comment]
now its okay, for some reason, it happened for like 2 hours and then it
stopped happening

**Comment by Hawk768** [comment]
Yes somehow for me it's working again

**Comment by nahuhh** [comment]
Same problem, tried to install and uninstall all 3 apks.

What worked for me was to install the same ask twice. In my case, the arm64
