### ISSUE TITLE
It's broken, waiting for it to be updated.

### ISSUE THREAD

**Issue by 7thghoul** [mukul500/AnimeXStream#157]
![Screenshot_20201206-235316_Anime X Stream.jpg](https://user-images.githubusercontent.com/64592521/101288768-4c95eb80-381e-11eb-8de0-116950c07b25.jpg)![Screenshot_20201206-235332_Anime X Stream.jpg](https://user-images.githubusercontent.com/64592521/101288777-528bcc80-381e-11eb-9f9f-b8b9767c782d.jpg)

**Comment by MonsieurGuepard** [comment]
Same here, galaxy s10+

**Comment by danielr0206** [comment]
Try reinstalling the app cuz it works fine for me 
Android 5

**Comment by RealFeorache** [comment]
same for op5
