### ISSUE TITLE
need help for app , api releted query(need help)

### ISSUE THREAD

**Issue by govind1530** [mukul500/AnimeXStream#159]
I want to also create an app for anime, I have some ideas, but I don't have an API or database for anime, can you please guide what service you use in your app video, list etc. it will be really helpful thanks.

**Comment by harshal-99** [comment]
He has listed [technologies](https://github.com/mukul500/AnimeXStream#technologies-used) he has used to write this app and I think he is using GoAnime API, you can always go through the code base if you know how to develop android apps.

**Comment by govind1530** [comment]
I don't have any native knowledge about android/ios.  only knowledge about react-native, but thanks I look into it.
