### ISSUE TITLE
No internet connection

### ISSUE THREAD

**Issue by Rezert-g** [mukul500/AnimeXStream#160]
This is only happening on the first episodes of any anime I try to watch but it tells me no internet connection even though I can watch the rest of the episodes

**Comment by aternativ** [comment]
I can't watch any episodes

**Comment by ashmitsinghsaggu** [comment]
Sed

**Comment by Rezert-g** [comment]
> Sed

?

**Comment by harshal-99** [comment]
>sed 


is sarcastic way of saying sad.
