### ISSUE TITLE
Unable to run any episode or anime

### ISSUE THREAD

**Issue by msoriginal** [mukul500/AnimeXStream#171]
I am unable to search or play any episode. In other words App is not working. Only home page opens. I observed that there is specific website, when it is down the app also don't work. At the same time some other url for same website works.
So i want to know the piece of code where url is written and want to change it.

**Comment by Sudip909** [comment]
Unable to open anime and much bug surver fix please

**Comment by Xenonyxes** [comment]
Same every time I load an ep it's says: sever is down pleas retry

**Comment by ckonar92** [comment]
Same here, can someone please fix it

**Comment by Sudip909** [comment]
No sar always surver good but February 1st day suddenly closed my anime
xstream apk, and don't open this app please fix it 🙏🏻😭😭😭😭😭

**Comment by harshal-99** [comment]
This one is working https://github.com/vapormusic/AnimeXStream

**Comment by Sudip909** [comment]
No not working, but Feb 1st day all works, fix it as soon as possible
please 🙏🏻🙏🏻🙏🏻🙏🏻🙏🏻😭😭😭😭😭😭

**Comment by ckonar92** [comment]
@mukul500 buddy please fix it, much appreciated

**Comment by Sudip909** [comment]
Thank you very much for the bug fix
