### ISSUE TITLE
Server error

### ISSUE THREAD

**Issue by Fatashio** [mukul500/AnimeXStream#172]
I cant watch or finish my latest anime I'm watching I love animexstream please fix it my guy
It keeps saying server error repeatedly is there a update?

**Comment by Rezert-g** [comment]
the last commit was five months ago I don't think we're getting an update

**Comment by mukul500** [comment]
I will try to fix this next weekend Will provide a working APK

**Comment by aternativ** [comment]
love you mukul

**Comment by Rezert-g** [comment]
> I will try to fix this next weekend Will provide a working APK

thanks

**Comment by anindya127** [comment]
#177

**Comment by anindya127** [comment]
#177
