### ISSUE TITLE
App Problem

### ISSUE THREAD

**Issue by DreamPenguinAlt** [mukul500/AnimeXStream#175]
For some reason whenever i wanna watch or search something it just basically turns blank and i tried overwriting the installlation of older versions but it turns out not being able to be installed
![Screenshot_20210206-072741_Anime X Stream](https://user-images.githubusercontent.com/66594719/107099617-19d39800-684d-11eb-8914-897d4a9976f9.jpg)
![Screenshot_20210206-072758_Anime X Stream](https://user-images.githubusercontent.com/66594719/107099624-20620f80-684d-11eb-9a4d-aa6a2f248ece.jpg)

**Comment by saurabhraj042** [comment]
@mukul500  I would like to work on this issue :O ,
