### ISSUE TITLE
To those who are facing server problem

### ISSUE THREAD

**Issue by an1k3tt** [mukul500/AnimeXStream#177]
Contact the creator and someone please confirm is a update is coming or not😭
![Pain Nagato ](https://user-images.githubusercontent.com/70314421/107118360-9f376680-68a6-11eb-9e2d-ab12d2e7f9d7.jpg)

http://www.facebook.com/xblackyy

**Comment by ShisheerRSHETTY** [comment]
Please fix Anime x stream is not working
