### ISSUE TITLE
App not working 😕 

### ISSUE THREAD

**Issue by uddipon2000** [mukul500/AnimeXStream#181]

**Comment by aternativ** [comment]
We get it bro, you don't have to open 4 additional threads to the others stating the same thing lol

**Comment by uddipon2000** [comment]
Can you pls say when will this problem fix 🙏🙏
This is the most important app in my phone can't live without it

**Comment by aternativ** [comment]
I'm not a dev. I feel the same way as you but mukul said he's working on it and is trying to bring it back this weekend

**Comment by uddipon2000** [comment]
Great news 👍👍

**Comment by harshal-99** [comment]
Until it's fixed you can use this https://github.com/vapormusic/AnimeXStream

**Comment by uddipon2000** [comment]
Thx bro

**Comment by uddipon2000** [comment]
Can you suggest similar type of app but to watch movie

**Comment by aternativ** [comment]
nah i only use this one too

În dum., 7 feb. 2021 la 16:01, uddipon2000 <notifications@github.com> a
scris:

**Comment by harshal-99** [comment]
> Can you suggest similar type of app but to watch movie

Search berg apk on Google

**Comment by mukul500** [comment]
> Until it's fixed you can use this https://github.com/vapormusic/AnimeXStream

Don't Use any third APK, It will make lose all your Favourites Anime & All Anime Progress

**Comment by aternativ** [comment]
bruh i already used it

**Comment by anindya127** [comment]
> > Until it's fixed you can use this https://github.com/vapormusic/AnimeXStream
> 
> Don't Use any third APK, It will make lose all your Favourites Anime & All Anime Progress

The app is not as great as the original one.

**Comment by anindya127** [comment]
> Can you suggest similar type of app but to watch movie

https://cinemaapk.com/

You can see movies and tv shows by using this app

**Comment by vapormusic** [comment]
> > Until it's fixed you can use this https://github.com/vapormusic/AnimeXStream
> 
> Don't Use any third APK, It will make lose all your Favourites Anime & All Anime Progress

man update your build please, I hate to make my own fork and maintain it

**Comment by dstasio** [comment]
The only problem is that gogoanime's domain changed. I've successfully fixed it in my fork (haven't committed yet though), but I also renamed the app so favourites and progress don't carry over.
If @mukul500 is unable to fix it for the time being, I could make a build with the same name to keep old data.

**Comment by vapormusic** [comment]
> The only problem is that gogoanime's domain changed. I've successfully fixed it in my fork (haven't committed yet though), but I also renamed the app so favourites and progress don't carry over.
> If @mukul500 is unable to fix it for the time being, I could make a build with the same name to keep old data.

You can send a pull request to him .... and btw , his apk and your apk has different signatures so old data wont be saved

**Comment by dstasio** [comment]
> > The only problem is that gogoanime's domain changed. I've successfully fixed it in my fork (haven't committed yet though), but I also renamed the app so favourites and progress don't carry over.
> > If @mukul500 is unable to fix it for the time being, I could make a build with the same name to keep old data.
> 
> You can send a pull request to him .... and btw , his apk and your apk has different signatures so old data wont be saved

I meant in case he can't access his computer for some reason, or something like that which prevents him from making a build.
Didn't know about the signature, nvm then.

**Comment by mukul500** [comment]
Guys no need to update APK. I have updated the domain name on Firebase Remote Config. Try and open and close your app 1-2 times. So gogoanime domains get updated. It will works fine.

**Comment by uddipon2000** [comment]
Great
