### ISSUE TITLE
loading 

### ISSUE THREAD

**Issue by Rezert-g** [mukul500/AnimeXStream#182]
does anyone else get long loading times and then once it plays for a few seconds it goes back to loading

**Comment by Rezert-g** [comment]
it stopped but I'm not able to watch certain episodes it doesn't load![Screenshot_20210207-213156.png](https://user-images.githubusercontent.com/67710243/107172822-ed726580-698b-11eb-82da-8952dc85d2db.png)

**Comment by Rezert-g** [comment]
> it stopped but I'm not able to watch certain episodes it doesn't load![Screenshot_20210207-213156.png](https://user-images.githubusercontent.com/67710243/107172822-ed726580-698b-11eb-82da-8952dc85d2db.png)

this is only happening for mushoku tensei: isekai episode 5

**Comment by Rezert-g** [comment]
> > it stopped but I'm not able to watch certain episodes it doesn't load![Screenshot_20210207-213156.png](https://user-images.githubusercontent.com/67710243/107172822-ed726580-698b-11eb-82da-8952dc85d2db.png)
> 
> this is only happening for mushoku tensei: isekai episode 5

I have figured out it's not the anime it's the next episode button I use when it's the last episode. it stays like what the image above is so idk why this is happening

**Comment by mukul500** [comment]
Fixed Just open and close app 2-3 times it will work fine.
