### ISSUE TITLE
If your app still not working properly

### ISSUE THREAD

**Issue by tatsune38** [mukul500/AnimeXStream#183]
for the past days the app gone broken for some reason and stuck at server error, not showing up some searches and not showing the episode lists. Somehow it worked again after updating the app with the same apk I installed with it, hope it helps you guys

**Comment by mukul500** [comment]
Actually i fixed the isdue from backend. All installed apk should work fine by now

**Comment by mukul500** [comment]
Fixed Just open and close app 2-3 times it will work fine.
