### ISSUE TITLE
App works then doesnt

### ISSUE THREAD

**Issue by wolfyrevived** [mukul500/AnimeXStream#186]
It wasnt working at first gave the error message when pressing play and there wasnt a list of episodes for the shows. Thsn it worked for about a month and now all of a sudden just stopped and the old problems are back nothing works but the opening page

**Comment by mrpoophead** [comment]
Try to download it with the same apk you use to install it it work for me but it's doing the same thing again 😿

**Comment by mukul500** [comment]
Fixed Just open and close app 2-3 times it will work fine.
