### ISSUE TITLE
App stops working after initial install. 

### ISSUE THREAD

**Issue by Alexbramos63** [mukul500/AnimeXStream#192]
Well the app stopped working about two weeks ago. The only time I get it to work is if I uninstall then reinstall the app. Once the app is opened the first time after reinstall it works. And it will continue to work until I close the app. 
 But once I close it then reopen it later. Server error or black screen. Then to view again, I must uninstall then reinstall all over again.

**Comment by anindya127** [comment]
Hey thanks man.. But don't uninstall the app just clear the data. It will work.

**Comment by Alexbramos63** [comment]
OK thanks
