### ISSUE TITLE
Clear the app data and it should work but you have to clear it every time you close it.... 

### ISSUE THREAD

**Issue by anindya127** [mukul500/AnimeXStream#193]
I cleaned my app data and it is working fine but you have do it every time you close the app. 😥😥

**Comment by AlphaCODM** [comment]
Thanks for the idea. Its Working now😁. Also its working normally even after i reopened it after closing. Anyway thanks❤️

**Comment by AlphaCODM** [comment]
Mukul500 big salute to you man. You're a legend🔥🔥
