### ISSUE TITLE
app not working atm :(

### ISSUE THREAD

**Issue by amazonalex** [mukul500/AnimeXStream#198]
Hey, i dont know if I'm the only one with this issue, but the app isnt working right now. I click on an episode, and it says "something went wrong" instead. I try searching up series, but it shows up blank, same with clicking different series of anime! please fix this🙏

**Comment by Raheemshah2809** [comment]
Yea same for me, thought it was just my app,

**Comment by dhljt** [comment]
Yes, still not working for me, same problem :{

**Comment by amazonalex** [comment]
>
