### ISSUE TITLE
Server error

### ISSUE THREAD

**Issue by reina48** [mukul500/AnimeXStream#21]
I don't know if it just me, but everytime I open a new episode, it displayed "server error"..and also the server are kinda bad lately but I'm kinda okay with that tho..thank you so much for this great app 😊

**Comment by mukul500** [comment]
Can u describe in detail. Which episode and anime. You are getting server error

**Comment by reina48** [comment]
Ah it was IDOLiSH7 second beat..but I've tried restarting my phone and I can play it back after that..maybe its my phone probs or some kind of bugs but it's okay now :) sorry for any inconveniences

**Comment by mukul500** [comment]
A new version is out[ Download ](https://github.com/mukul500/AnimeXStream/releases/tag/v0.4.0) .That fixes all issues, Update your app to the latest version
