### ISSUE TITLE
The rounded corner problem

### ISSUE THREAD

**Issue by DoggoOfSpeed** [mukul500/AnimeXStream#24]
So I've noticed that the app rounds out the corners of what you are watching. That really wouldn't be a problem, but when whatching through PiP mode, the cut coners can become quite obvious. Of course it would still be possible to round the corners when watching in fullscreen, but is it really necessery? If yes, then that would have to be an option in a settings menu.

**Comment by mukul500** [comment]
A new version is out[ Download ](https://github.com/mukul500/AnimeXStream/releases/tag/v0.4.0) .That fixes all issues, Update your app to the latest version
