### ISSUE TITLE
New App With No Issues! Download Here! V3.0.6. (I've tried it myself, it's 100% working!) Fixed Link.

### ISSUE THREAD

**Issue by G0J0N0M** [mukul500/AnimeXStream#258]
Download AnimeXStream v3.0.6: https://www.mediafire.com/file/9g6hr83s2iir71a/AnimexStream-v3.0.6-universal-release.apk/file

_**Your welcome!**_

**Comment by Dewet-sa** [comment]
I get a 404

Did something change

**Comment by G0J0N0M** [comment]
Thats weird. The link was working yesterday for me. Maybe the owner by vapormusic removed it.

**Comment by G0J0N0M** [comment]
Here. I uploaded the apk

**Comment by Dewet-sa** [comment]
Thanks a milli
