### ISSUE TITLE
Modularity support such as Tachiyomi

### ISSUE THREAD

**Issue by gibcheesepuffs** [mukul500/AnimeXStream#26]
Have you seen Tachiyomi? If you have used it you already know what I mean. Maybe we can have support for more servers/services easily if you add functionality of adding more servers in form of modules packaged as APK packages in a repository. This will make it easy for the community to work on this project. There are so many servers/services so that if one goes down user can just install a module from within the app to switch server/service and you won't have to patch the main app if API implementation of one service changes, just update the package and release it in repo.

**Comment by DoggoOfSpeed** [comment]
So basically like AniLabX?

**Comment by shoukolate** [comment]
I have not used AniLabX so I am unaware of it.

**Comment by mukul500** [comment]
I am unware of these how this works but will give a look

**Comment by GoluLiliput** [comment]
Lol rilly guys... AniLabX is super nonsense app. Many apps way better than that can be found on playstore. 
And this app does the job the most smoothest and reliably. Tho more servers can be added in this app, but this app is the most no-nonsense anime app ever. I have like literally used hundreds of anime streaming app
