### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by anindya127** [mukul500/AnimeXStream#268]
Hey guys i am using Xiaomi note 7 pro with miui 12.5  Chinese rom (rooted) and android 10.
After the app went down a couple of weeks ago i couldn't use the  app any monre. I saw some one poster a mod version of the app (3.0.6) and i aslo tried that but nothing working for me. I was with this app from 0.2.2 and i love this app so much. I know there are similar apps and more good anime streaming app out there but i still love this app. So if anyone can solve/fix my problem i will be grateful to them.Thank you.
![Screenshot_2021-07-11-18-46-20-325_net xblacky animexstream](https://user-images.githubusercontent.com/70308564/125195637-55e5ab80-e278-11eb-8936-a4f5d1303f8c.jpg)
![Screenshot_2021-07-11-18-46-30-158_net xblacky animexstream](https://user-images.githubusercontent.com/70308564/125195639-58e09c00-e278-11eb-9b3d-d6aa15f52c68.jpg)

**Comment by mukuI500** [comment]
AnimeXStream Version 3.0.6 works for everyone. So its only yours not working. Try download again v.3.0.6
AnimeXStream: https://www.mediafire.com/file/9g6hr83s2iir71a/AnimexStream-v3.0.6-universal-release.apk/file

**Comment by anindya127** [comment]
Yes it's working but i need a vpn connection.
