### ISSUE TITLE
[Bug] Search Result List is leaving Space in UI

### ISSUE THREAD

**Issue by Ghoul2077** [mukul500/AnimeXStream#28]
<p>When I search for any anime the search result list is compacted towards the left and leaving some empty space to the right contrary to the images from the README, for more clarity here is the screenshots</p>
<p>
<img src="https://user-images.githubusercontent.com/42601281/79537385-cca8ee80-809f-11ea-994e-67ffcbbeda87.png" width=270 height=540>
<b>VS</b>
<img src="https://raw.githubusercontent.com/mukul500/AnimeXStream/dev/meta/android/screenshots/screenshot_09.jpg" width=270 height=540>
</p>
<p>My device is the left and the right one is how it should look (from README.md) , I think this might be due to 18:9 aspect ratio of my device</p>
<p>Device Name :- Redmi 5</p>
<p>Android Version :- 10 </p>
<p> Version of App :- 0.2.0 </p>

**Comment by mukul500** [comment]
It's because of zoom settings in android. Go to your phone settings -> Display -> Screen zoom (Change it to negative- ) .

**Comment by Ghoul2077** [comment]
Changing the display size does seem to fit the content horizontally but makes everything else on my device very small. The above screenshot has default zoom for my device.
Maybe in case of bigger dpi the list could be made bigger or smaller as to fill the space completely

**Comment by mukul500** [comment]
A new version is out[ Download ](https://github.com/mukul500/AnimeXStream/releases/tag/v0.4.0) .That fixes all issues, Update your app to the latest version
