### ISSUE TITLE
Okay attention everyone

### ISSUE THREAD

**Issue by Aftabyasir9** [mukul500/AnimeXStream#286]
Everyone please listen out to me, I am Yasir Aftab, I don't have much experience in coding, but this is a free source app and we can re-code it and add a login system ourselves. I have contacted the developer and he says that he can't make enough time to work on the update but I got his permission for the login feature addon.
Anyone interested please contact here
https://instagram.com/yasir_ali_999?utm_medium=copy_link
I am hoping help

**Comment by mukul500** [comment]
A new version is out[ Download ](https://github.com/mukul500/AnimeXStream/releases/tag/v0.4.0) .That fixes all issues, Update your app to the latest version
