### ISSUE TITLE
Server issue

### ISSUE THREAD

**Issue by kira910** [mukul500/AnimeXStream#288]
I Can't watch it keeps saying server error do you guy have the same problem?
![Screenshot_2021-09-07-13-01-44-224_net vapormusic animexstream](https://user-images.githubusercontent.com/86780850/132286975-f014a5e6-5936-41cb-a2da-d8aedcc38349.jpg)

**Comment by ElezeoraDraconius** [comment]
Hi..i got the same problem just now but already fixed.. Try uninstalling and installing the app again..
