### ISSUE TITLE
[Bug] Player Automatically Resumes when any notification is Received

### ISSUE THREAD

**Issue by Ghoul2077** [mukul500/AnimeXStream#29]
<p>When the player is paused and I receive a notification on any other app (for eg. on whatsapp) the player will automatically resume the video.<p>
<p>Device :- Redmi 5</p>
<p>Android Version :- 10</p>
<p>App Version :- 0.2.0</p>

**Comment by mukul500** [comment]
A new version is out[ Download ](https://github.com/mukul500/AnimeXStream/releases/tag/v0.4.0) .That fixes all issues, Update your app to the latest version
