### ISSUE TITLE
Server error, again

### ISSUE THREAD

**Issue by ElezeoraDraconius** [mukul500/AnimeXStream#290]
Not even uninstalling and installing it back again seems to fix this issue this time so😭

**Comment by noobie13** [comment]
> Not even uninstalling and installing it back again seems to fix this issue this time so😭

Yeah same happening with me too

**Comment by noobie13** [comment]
> So i tried uninstalling and installing it for the last time hoping for some miracle.. It finally worked😷

Are you using Version 3.0.6 ?

**Comment by ElezeoraDraconius** [comment]
Yea version3. 0.6.

**Comment by noobie13** [comment]
> Ok so it turns out some anime will play and some will display "server error "

Ahh crap. I tried reinstalling couple of times too. It didn't work 😭

**Comment by Aftabyasir9** [comment]
We can't do anything but wait for the developer to fix it or rather it gets fixed on it's own

**Comment by noobie13** [comment]
> We can't do anything but wait for the developer to fix it or rather it gets fixed on it's own

The developer has stopped working on the app most probably 😭

**Comment by Aftabyasir9** [comment]
I have contacted him personally, let's wait for his reply, he has stopped working on updates, but he said that he will still fix the issues ✌️

**Comment by Drxco4** [comment]
Same L

**Comment by ElezeoraDraconius** [comment]
Hope this app get fixed.. This app is literally the best app ever

**Comment by jirali** [comment]
What do you mean version 3.0.6? I only see version 0.2.4.

**Comment by mukul500** [comment]
The issue is resolved now, [Download v0.2.5](https://github.com/mukul500/AnimeXStream/releases)
