### ISSUE TITLE
Whenever I am going to watch Any anime, it's showing server problem

### ISSUE THREAD

**Issue by soymadip** [mukul500/AnimeXStream#296]
Whenever I am going to watch anime, it's showing server problem notice

**Comment by Drxco4** [comment]
Same

**Comment by Adithl** [comment]
Im also having the same problem.

**Comment by Adithl** [comment]
Why cant they just fix everything.

**Comment by Rezert-g** [comment]
> Why cant they just fix everything.

In coding new problems show up everyday its nearly impossible to get a perfect code that will never have to be fixed or have any bugs.

**Comment by kira910** [comment]
I think every server thats connect in animexstream is down thats why some are still playing and some are not

**Comment by Adithl** [comment]
Ohh

**Comment by kira910** [comment]
Guys pls if you find a good app to watch anime plss tell me

**Comment by pokurt** [comment]
@Adithl  @kira910 im really sorry for a late update. i have opened a pr right here: https://github.com/mukul500/AnimeXStream/pull/304 i also maintain a fork while fixing these things as fast as possible. i hope this would be an efficient fix for animeXstream and forks

**Comment by mukul500** [comment]
The issue is resolved now, [Download v0.2.5](https://github.com/mukul500/AnimeXStream/releases)
