### ISSUE TITLE
Server error.

### ISSUE THREAD

**Issue by itsMeMario69** [mukul500/AnimeXStream#298]
It doesn't load. Tried re-installing and clearing data, still doesn't work. Please fix it soon. ❤️
![Screenshot_2021-09-11-00-31-33-922_net vapormusic animexstream](https://user-images.githubusercontent.com/82156197/132902608-090c546f-5266-4b54-bfc6-73a61ee22cee.jpg)

**Comment by mukul500** [comment]
The issue is resolved now, [Download v0.2.5](https://github.com/mukul500/AnimeXStream/releases)
