### ISSUE TITLE
Server error issue

### ISSUE THREAD

**Issue by h1ntaruto** [mukul500/AnimeXStream#300]
Some of the assets are also undownloadable.

**Comment by stark-cpu** [comment]
Same server error

**Comment by pokurt** [comment]
dont worry, as soon as app dev will merge this https://github.com/mukul500/AnimeXStream/pull/304 users will be able to receive updates

**Comment by Aftabyasir9** [comment]
> dont worry, as soon as app dev will merge this #304 users will be able to receive anime

Thank you so much Mr Pokurt, we were waiting for support. I hope things go back to normal soon as the files get updated.

**Comment by mukul500** [comment]
The issue is resolved now, [Download v0.2.5](https://github.com/mukul500/AnimeXStream/releases)
