### ISSUE TITLE
Funimation shutting down illegal anime apps

### ISSUE THREAD

**Issue by kira910** [mukul500/AnimeXStream#301]
They said that funimation is shutting down illegal anime apps search it in facebook if you don't believe me

![IMG_20210911_235651](https://user-images.githubusercontent.com/86780850/132953823-5bc79f91-ff00-4b90-a681-bab22db47a49.jpg)

**Comment by itsMeMario69** [comment]
Damn, thats sad. :(

**Comment by mukul500** [comment]
The issue is resolved now, [Download v0.2.5](https://github.com/mukul500/AnimeXStream/releases)
