### ISSUE TITLE
PLEASE FIX SERVER ERROR

### ISSUE THREAD

**Issue by Carnaken** [mukul500/AnimeXStream#302]
This is app is my most favorite because it easy to use and not laggy unlike aniyomi hope you fix it as fast as u can.

**Comment by pokurt** [comment]
it will be fixed. be patient: https://github.com/mukul500/AnimeXStream/pull/304

**Comment by stark-cpu** [comment]
![Screenshot_2021-09-17-20-48-50-373_net xblacky animexstream](https://user-images.githubusercontent.com/90656285/133807688-6c94128f-b2fd-47ae-a9b7-dcc037271883.png)
Please sir how much time to fix this problem

**Comment by mukul500** [comment]
The issue is resolved now, [Download v0.2.5](https://github.com/mukul500/AnimeXStream/releases)
