### ISSUE TITLE
When will it be fixed?

### ISSUE THREAD

**Issue by itsMeMario69** [mukul500/AnimeXStream#303]
Been 4-5 days. It shows server error while opening an anime. Very few can be played though. Please fix it soon.❤️
![Screenshot_2021-09-13-10-19-06-868_net vapormusic animexstream](https://user-images.githubusercontent.com/82156197/133024485-9a848462-9933-4ce5-bc49-452013eb555e.jpg)

**Comment by pokurt** [comment]
Soon: https://github.com/mukul500/AnimeXStream/pull/304

**Comment by h1ntaruto** [comment]
Is that actually you mikul?

**Comment by mukul500** [comment]
The issue is resolved now, [Download v0.2.5](https://github.com/mukul500/AnimeXStream/releases)
