### ISSUE TITLE
Anime x stream app error

### ISSUE THREAD

**Issue by 13thamayun** [mukul500/AnimeXStream#306]
![Screenshot_20210915-215833_Anime X Stream](https://user-images.githubusercontent.com/90797582/133508718-94ba757c-b54d-4086-ba58-da0ed541a36a.jpg)

**Comment by demigodflash** [comment]
Plaese fix this how much time more

**Comment by mukul500** [comment]
The issue is resolved now, [Download v0.2.5](https://github.com/mukul500/AnimeXStream/releases)
