### ISSUE TITLE
Server error

### ISSUE THREAD

**Issue by stark-cpu** [mukul500/AnimeXStream#307]
![Screenshot_2021-09-17-20-48-50-373_net xblacky animexstream](https://user-images.githubusercontent.com/90656285/133807881-57cdd17a-8696-487f-98ef-d70f84d623ad.png)
Please sir how much time to fix this problem.
Some anime are playing but the anime series I am watching is not playing @mukul500

**Comment by mukul500** [comment]
The issue is resolved now, [Download v0.2.5](https://github.com/mukul500/AnimeXStream/releases)
