### ISSUE TITLE
App keeps crashing after v0.2.5 update

### ISSUE THREAD

**Issue by ecodulio** [mukul500/AnimeXStream#309]
Can't open the app anymore after the update.

**Comment by harshal-99** [comment]
Crash log url for my device [Link](https://hastebin.com/idilodotoh)

**Comment by gammergg** [comment]
+1

**Comment by mukul500** [comment]
The issue is Fixed I have updated the newer APK in same release[ Download and reinstall v0.2.5](https://github.com/mukul500/AnimeXStream/releases/)
