### ISSUE TITLE
App doesn't open.

### ISSUE THREAD

**Issue by gammergg** [mukul500/AnimeXStream#312]
The app is not even opening in v0.2.5 anymore. Plz look into it. @mukul500

**Comment by mukul500** [comment]
@gammergg Don't give me heartattack xD

**Comment by gammergg** [comment]
> @gammergg Don't give me heartattack xD

Lol I forgot to add "not"😂

**Comment by mukul500** [comment]
The issue is Fixed I have updated the newer APK in same release[ Download and reinstall v0.2.5](https://github.com/mukul500/AnimeXStream/releases/)
