### ISSUE TITLE
App crashes

### ISSUE THREAD

**Issue by kl3jvi** [mukul500/AnimeXStream#313]
v0.2.5 app doesnt open and it crashes immediately

**Comment by adangster1** [comment]
Same here.. Android 11..security  updated August 1 2021 (latest). App worked on last version.

**Comment by mukul500** [comment]
The issue is Fixed I have updated the newer APKin same release[ Download and reinstall v0.2.5](https://github.com/mukul500/AnimeXStream/releases/)
