### ISSUE TITLE
I cant open the app after 2.5 update

### ISSUE THREAD

**Issue by Carnaken** [mukul500/AnimeXStream#314]
![Screenshot_2021_0920_203756](https://user-images.githubusercontent.com/81844464/133996346-a0b1f8ed-7589-480d-8888-29f72fd38d2f.jpg)

I tried all the new apk, all of them cant open the app.
![Screenshot_2021_0920_203756](https://user-images.githubusercontent.com/81844464/133996413-127aed34-1b4a-4228-89b2-41f604ce3aa7.jpg)

**Comment by DerrenTuscano** [comment]
How to update the app ?

**Comment by mukul500** [comment]
The issue is Fixed I have updated the newer APKin same release[ Download and reinstall v0.2.5](https://github.com/mukul500/AnimeXStream/releases/)
