### ISSUE TITLE
App Crash

### ISSUE THREAD

**Issue by LFFTY** [mukul500/AnimeXStream#324]
The app keeps crashing after pressing the back button. This only occurs after searching for an anime. 

https://user-images.githubusercontent.com/91778853/135709634-bd193b83-8e63-4393-9316-cd7a8b6fca91.mp4

**Comment by mukul500** [comment]
A new version is out[ Download ](https://github.com/mukul500/AnimeXStream/releases/tag/v0.4.0) .That fixes all issues, Update your app to the latest version
