### ISSUE TITLE
Failed to read key debug from store

### ISSUE THREAD

**Issue by githubashutoshsoni** [mukul500/AnimeXStream#33]
PS i'm a Noob. So, I'm building the project in my android studio and I keep getting this error. what should I do 
`Failed to read key debug from store "C:\Users\Soni\Downloads\Big Project\AnimeXStream\debug_keys.jks": null`
I created a file debug_keys.jks.

1.  file->project structure->modules->signing configs->
2. did release and debug version with some keys and values.
3. clicked ok. and tried to build again.
4. same thing. What am I doing wrong?

How can I build it in  my android studio?

**Comment by crazyuploader** [comment]
You can run in your project's root folder to see what's wrong
`gradlew signingReport`

**Comment by githubashutoshsoni** [comment]
Ok I did and this is almost same as what it was throwing me in the logs of android studio. 

```
Starting a Gradle Daemon, 2 incompatible and 2 stopped Daemons could not be reused, use --status for details

> Task :app:signingReport
Variant: debugUnitTest
Config: release
Store: C:\Users\Soni\Downloads\Big Project\AnimeXStream\debug_keys.jks
Alias: debug
Error: Failed to read key debug from store "C:\Users\Soni\Downloads\Big Project\AnimeXStream\debug_keys.jks": null
----------
Variant: debugAndroidTest
Config: release
Store: C:\Users\Soni\Downloads\Big Project\AnimeXStream\debug_keys.jks
Alias: debug
Error: Failed to read key debug from store "C:\Users\Soni\Downloads\Big Project\AnimeXStream\debug_keys.jks": null
----------
Variant: release
Config: release
Store: C:\Users\Soni\Downloads\Big Project\AnimeXStream\debug_keys.jks
Alias: debug
Error: Failed to read key debug from store "C:\Users\Soni\Downloads\Big Project\AnimeXStream\debug_keys.jks": null
----------
Variant: releaseUnitTest
Config: release
Store: C:\Users\Soni\Downloads\Big Project\AnimeXStream\debug_keys.jks
Alias: debug
Error: Failed to read key debug from store "C:\Users\Soni\Downloads\Big Project\AnimeXStream\debug_keys.jks": null
----------
Variant: debug
Config: release
Store: C:\Users\Soni\Downloads\Big Project\AnimeXStream\debug_keys.jks
Alias: debug
Error: Failed to read key debug from store "C:\Users\Soni\Downloads\Big Project\AnimeXStream\debug_keys.jks": null
----------

BUILD SUCCESSFUL in 9s
1 actionable task: 1 executed
C:\Users\Soni\Downloads\Big Project\AnimeXStream>                                                                                                                                                                                               
```

**Comment by crazyuploader** [comment]
> Ok I did and this is almost same as what it was throwing me in the logs of android studio. 
> 
> ```
> Starting a Gradle Daemon, 2 incompatible and 2 stopped Daemons could not be reused, use --status for details
> 
> > Task :app:signingReport
> Variant: debugUnitTest
> Config: release
> Store: C:\Users\Soni\Downloads\Big Project\AnimeXStream\debug_keys.jks
> Alias: debug
> Error: Failed to read key debug from store "C:\Users\Soni\Downloads\Big Project\AnimeXStream\debug_keys.jks": null
> ----------
> Variant: debugAndroidTest
> Config: release
> Store: C:\Users\Soni\Downloads\Big Project\AnimeXStream\debug_keys.jks
> Alias: debug
> Error: Failed to read key debug from store "C:\Users\Soni\Downloads\Big Project\AnimeXStream\debug_keys.jks": null
> ----------
> Variant: release
> Config: release
> Store: C:\Users\Soni\Downloads\Big Project\AnimeXStream\debug_keys.jks
> Alias: debug
> Error: Failed to read key debug from store "C:\Users\Soni\Downloads\Big Project\AnimeXStream\debug_keys.jks": null
> ----------
> Variant: releaseUnitTest
> Config: release
> Store: C:\Users\Soni\Downloads\Big Project\AnimeXStream\debug_keys.jks
> Alias: debug
> Error: Failed to read key debug from store "C:\Users\Soni\Downloads\Big Project\AnimeXStream\debug_keys.jks": null
> ----------
> Variant: debug
> Config: release
> Store: C:\Users\Soni\Downloads\Big Project\AnimeXStream\debug_keys.jks
> Alias: debug
> Error: Failed to read key debug from store "C:\Users\Soni\Downloads\Big Project\AnimeXStream\debug_keys.jks": null
> ----------
> 
> BUILD SUCCESSFUL in 9s
> 1 actionable task: 1 executed
> C:\Users\Soni\Downloads\Big Project\AnimeXStream>                                                                                                                                                                                               
> ```

You properly sat an alias key and password for the same?

**Comment by githubashutoshsoni** [comment]
I tried both ways. same password for alias key. different password for alias key. let me do it once again..

**Comment by githubashutoshsoni** [comment]
well, it's the same issue.
```
 release {
        storeFile file('C:\\Users\\Soni\\Downloads\\Big Project\\AnimeXStream\\debug.jks')
        storePassword 'release100'
        keyAlias = 'key01'
        keyPassword 'pkra8949'
    }
```

I've deleted the keys and created it again with diffenent file name and password, with different key name and key password. But still same error...  

`Failed to read key key01 from store "C:\Users\Soni\Downloads\Big Project\AnimeXStream\debug.jks": null`

**Comment by githubashutoshsoni** [comment]
Now i get "Password verification failed". I tried to clean and rebuild the project.

**Comment by crazyuploader** [comment]
> Now i get "Password verification failed". I tried to clean and rebuild the project.

I tried deleting key store file, and regenerated it again, it was working fine for me. How are you generating key store file and which IDE you using?

**Comment by mukul500** [comment]
Please remove or comment signings config from app level gradle file.

signingConfigs {
        release {
            storeFile file('E:\\Projects\\animexstream.jks')
            storePassword '...'
            keyAlias = '..'
            keyPassword '..'
        }
    }

You need to comment this code.
And remove signing from release and debug variant.

**Comment by githubashutoshsoni** [comment]
Thanks Just it worked.
