### ISSUE TITLE
app crashing

### ISSUE THREAD

**Issue by jibek08** [mukul500/AnimeXStream#331]
hello!! i have a issue about the app, cuz when i search naruto for example then i click the wrong naruto series so i tapped the back button the app suddenly crashed thats the thing, hope u guys fix it soon and i believe in u guys!! i love ur app, and one more thing.. add a category tab so that we can see wut genre we want to watch. thants all thankss for readingg, just believe mah duddess!!

**Comment by mukul500** [comment]
A new version is out[ Download ](https://github.com/mukul500/AnimeXStream/releases/tag/v0.4.0) .That fixes all issues, Update your app to the latest version
