### ISSUE TITLE
Search bar crashs

### ISSUE THREAD

**Issue by adithnrevi** [mukul500/AnimeXStream#335]
Search and crash fix it?

**Comment by Sudip909** [comment]
Same as me my app crash too

**Comment by mukul500** [comment]
Fix is on the way

**Comment by Nazir78** [comment]
Try Universal Version It Maybe Fix The Problem

**Comment by Sudip909** [comment]
I have universal app but not working 😁😔

**Comment by Adithl** [comment]
Your typing the anime name with spelling mistake,
Just search it on google and copy paste the non spelling mistake name

**Comment by mukul500** [comment]
A new version is out[ Download ](https://github.com/mukul500/AnimeXStream/releases/tag/v0.4.0) .That fixes all issues, Update your app to the latest version
