### ISSUE TITLE
App stops working

### ISSUE THREAD

**Issue by Manniga** [mukul500/AnimeXStream#336]
Whenever i go to type an anime in it crashes for no reason it also does this when i wanna go back to the previous page.

**Comment by Nazir78** [comment]
Download Universal Version, It Will Fix The Problem

**Comment by mukul500** [comment]
A new version is out[ Download ](https://github.com/mukul500/AnimeXStream/releases/tag/v0.4.0) .That fixes all issues, Update your app to the latest version
