### ISSUE TITLE
[Bug] Playback/Server error

### ISSUE THREAD

**Issue by BlackFira** [mukul500/AnimeXStream#34]
Hello, ive been having many issues with episodes not playing, the app will goto the video player but you can't start the video, i don't think its a anime specific issue.

**Comment by mukul500** [comment]
Its a server issue. Server we are fetching media is currently down for some animes. I am adding multiple source option. Will provide update soon

**Comment by jerald-0306** [comment]
The app stops automatically

**Comment by mukul500** [comment]
A new version is out[ Download ](https://github.com/mukul500/AnimeXStream/releases/tag/v0.4.0) .That fixes all issues, Update your app to the latest version
