### ISSUE TITLE
It shows Chinese anime on the Dub section

### ISSUE THREAD

**Issue by anindya127** [mukul500/AnimeXStream#340]
I am having this issue where it shows Chinese anime on the dub section. I hope you could fix the problem.... 
![Screenshot_2021-11-01-16-07-44-966_net xblacky animexstream](https://user-images.githubusercontent.com/70308564/139655841-03dc24f2-0cc0-4e2c-abe6-e70f9d895ee0.jpg)

**Comment by kira910** [comment]
Umm how did you get it to be black mode? Mine is always in white mode

**Comment by MD77MD** [comment]
the same here... showing Chinese anime in place of dub anime

**Comment by mukul500** [comment]
A new version is out[ Download ](https://github.com/mukul500/AnimeXStream/releases/tag/v0.4.0) .That fixes all issues, Update your app to the latest version
