### ISSUE TITLE
choose default video quality 

### ISSUE THREAD

**Issue by MD77MD** [mukul500/AnimeXStream#343]
my internet bandwidth is very limited so i can only play video in lower resolution... however i can not change default video quality as it set to auto.. so i have to change the video resolution in every single video which is annoying 🙄 

also it would be a good idea to When a viewing session is started and the default video quality is changed... it should keep playing next videos with that same resolution regardless of default quality

**Comment by mukul500** [comment]
This feature is live on current version 0.4.0

**Comment by MD77MD** [comment]
@mukul500 
its not... for me it always switch back to auto... perhaps you explain to me how to set quality for example 480p
