### ISSUE TITLE
app crashing. 

### ISSUE THREAD

**Issue by zaiwick** [mukul500/AnimeXStream#344]
app auto close when i search for anime. sometimes auto close app itself. im using POCO F3 Device

**Comment by GSX-GAMER** [comment]
app auto close when i search for anime. sometimes auto close app itself. im using POCO K40 Device

**Comment by mukul500** [comment]
A new version is out[ Download ](https://github.com/mukul500/AnimeXStream/releases/tag/v0.4.0) .That fixes all issues, Update your app to the latest version
