### ISSUE TITLE
App is not working

### ISSUE THREAD

**Issue by pavanvarma98** [mukul500/AnimeXStream#347]
It is not showing any episodes in any anime

**Comment by HassanjX** [comment]
Yes true I was watching when at first the app said something went wrong and tried to open but episodes are not found !

**Comment by vikas-vky** [comment]
Same here. Tried uninstalling and reinstalling the app and also tried using a vpn, but no use. BTW hat are yo watching right now love to have some recommendations

**Comment by vikas-vky** [comment]
its up and working right now :-)

**Comment by VijaykumarBK** [comment]
Its crashing

**Comment by VijaykumarBK** [comment]
It's still crashing more than ever

**Comment by mukul500** [comment]
A new version is out[ Download ](https://github.com/mukul500/AnimeXStream/releases/tag/v0.4.0) .That fixes all issues, Update your app to the latest version
