### ISSUE TITLE
The episode list and details dont show up

### ISSUE THREAD

**Issue by Aaron2481** [mukul500/AnimeXStream#350]
I tap on an anime and nothing shows up

**Comment by Carnaken** [comment]
> I tap on an anime and nothing shows up

Update the app to 0.3.2

**Comment by minhperry** [comment]
0.3.2 and still not working

**Comment by mukul500** [comment]
A new version is out[ Download ](https://github.com/mukul500/AnimeXStream/releases/tag/v0.4.0) .That fixes all issues, Update your app to the latest version
