### ISSUE TITLE
The 0.3.2 UPDATE is so slow, Even though i have fast internet connection the video is always buffering. Please fix the server

### ISSUE THREAD

**Issue by Carnaken** [mukul500/AnimeXStream#351]
I have a good internet connection and i can watch 1080p to other websites without buffering. Please fix the server.

**Comment by VijaykumarBK** [comment]
Same problem

**Comment by razwatsup** [comment]
Keeps bufferring since last 2 updates..very bad. Never had such issues before

**Comment by AndyyAD** [comment]
Yes in my case after 7pm the videos buffer though i have good connection speed as Netflix run smoothly

**Comment by mukul500** [comment]
A new version is out[ Download ](https://github.com/mukul500/AnimeXStream/releases/tag/v0.4.0) .That fixes all issues, Update your app to the latest version
