### ISSUE TITLE
2 problems

### ISSUE THREAD

**Issue by AndyyAD** [mukul500/AnimeXStream#360]
1. When my phone is connected on call the video doesn't play. Actually me and my friends watch together on conference call and the video doesn't play please fix this as Netflix have very less anime.
2. I do not know whats wrong but at night after 7pm when i try to watch anime the videos always buffer. It keeps on buffering even at 360p but my internet connection is very good it even runs Netflix at around 720p.

**Comment by mukul500** [comment]
Will look at it

**Comment by mukul500** [comment]
A new version is out[ Download ](https://github.com/mukul500/AnimeXStream/releases/tag/v0.4.0) .That fixes all issues, Update your app to the latest version
