### ISSUE TITLE
Just in: SERVER ERROR

### ISSUE THREAD

**Issue by Carnaken** [mukul500/AnimeXStream#363]
Just in, app keeps saying its server error even though my internet is normal.

**Comment by Tesseract007** [comment]
Yes, Its the same for me

**Comment by edisontheking7** [comment]
me to but it because some error will come but my internet is a 1 ping bro

**Comment by edisontheking7** [comment]
and one more that is i think they will make a new update and the error be solved

**Comment by mukul500** [comment]
Fixed
