### ISSUE TITLE
JJK AND ONE PIECE NOT WORKING

### ISSUE THREAD

**Issue by AKASHGHISH** [mukul500/AnimeXStream#383]
Jjk is not working and one piece is only having 1080p quality plz fix this as soon as possible 👍

**Comment by 3008dead** [comment]
Not only it but in some episode like from 550+ it's having server issue in majority of episode . Please fix it

**Comment by mukul500** [comment]
A new version is out[ Download ](https://github.com/mukul500/AnimeXStream/releases/tag/v0.4.0) .That fixes all issues, Update your app to the latest version
