### ISSUE TITLE
Certain anime dont play

### ISSUE THREAD

**Issue by Manniga** [mukul500/AnimeXStream#385]
Im sure youve seen this just to let you know not all of them dont work certain ones like Tokyo revengers and black clover play but some like Assassination classroom and dr stone dont play :)

**Comment by ITADORI-15** [comment]
Same prob

**Comment by mukul500** [comment]
A new version is out[ Download ](https://github.com/mukul500/AnimeXStream/releases/tag/v0.4.0) .That fixes all issues, Update your app to the latest version
