### ISSUE TITLE
Videos aren't not playing

### ISSUE THREAD

**Issue by Guddu77788888** [mukul500/AnimeXStream#390]
Whenever I am opening an anime... The videos aren't not playing... Only the black screen is showing

**Comment by a3h1walker** [comment]
Same bro

**Comment by PainUzumaki** [comment]
Same bro I am watching Naruto Shippuden 😞😞 265 episode but his app crash ....

**Comment by anishfub2** [comment]
Same here, it's unable to stream any anime

**Comment by Axe090** [comment]
By the dev: "Gogoanime encyrpted all urls, will take time to fix"
Wait patiently until fixed.

**Comment by mukul500** [comment]
A new version is out[ Download ](https://github.com/mukul500/AnimeXStream/releases/tag/v0.4.0) .That fixes all issues, Update your app to the latest version
