### ISSUE TITLE
I am watching Naruto Shippuden 😞😞 265 episode but his app crash black Screen Showing 😞

### ISSUE THREAD

**Issue by PainUzumaki** [mukul500/AnimeXStream#391]

**Comment by Axe090** [comment]
By the dev: "Gogoanime encyrpted all urls, will take time to fix"
Wait patiently until fixed.

**Comment by mukul500** [comment]
A new version is out[ Download ](https://github.com/mukul500/AnimeXStream/releases/tag/v0.4.0) .That fixes all issues, Update your app to the latest version
