### ISSUE TITLE
Animes are not playing

### ISSUE THREAD

**Issue by Glyro** [mukul500/AnimeXStream#392]
I try so many anime and I also try delete app and agin install but nothing happens so the problem is in server I think app not playing any single anime
Repair it soon as possible

**Comment by Axe090** [comment]
By the dev: "Gogoanime encyrpted all urls, will take time to fix"
Wait patiently until fixed.

**Comment by mukul500** [comment]
A new version is out[ Download ](https://github.com/mukul500/AnimeXStream/releases/tag/v0.4.0) .That fixes all issues, Update your app to the latest version
