### ISSUE TITLE
Gogoanime old url in C.kt

### ISSUE THREAD

**Issue by jenlisabeth** [mukul500/AnimeXStream#393]
https://github.com/mukul500/AnimeXStream/blob/f098bb7707e1bb2ae4b3d20b43970cff53ac4ccd/app/src/main/java/net/xblacky/animexstream/utils/constants/C.kt#L14

Constant points to old url, updated url is: https://gogoanime.cm/

Might fix playback issues?

**Comment by ITADORI-15** [comment]
Damnn bro ur brainy af.. 
RESPECT ++

**Comment by mukul500** [comment]
A new version is out[ Download ](https://github.com/mukul500/AnimeXStream/releases/tag/v0.4.0) .That fixes all issues, Update your app to the latest version
