### ISSUE TITLE
Pls solve the problem of no Anime playing cos I'm watching one piece and it is not working.

### ISSUE THREAD

**Issue by Imkira18** [mukul500/AnimeXStream#397]

**Comment by AKASHGHISH** [comment]
Same bruh i was in ep 27 or something when the app shut downex

**Comment by Axe090** [comment]
By the dev: "Gogoanime encyrpted all urls, will take time to fix" 
Wait patiently until fixed.

**Comment by mukul500** [comment]
A new version is out[ Download ](https://github.com/mukul500/AnimeXStream/releases/tag/v0.4.0) .That fixes all issues, Update your app to the latest version
