### ISSUE TITLE
no video no timer , black screen 

### ISSUE THREAD

**Issue by Spyspring** [mukul500/AnimeXStream#399]
BLACK screen and no anime is working plss fix it asap

**Comment by pikachuak** [comment]
No playing any anime at all

**Comment by Axe090** [comment]
By the dev: "Gogoanime encyrpted all urls, will take time to fix" 
Wait patiently until fixed.

**Comment by mukul500** [comment]
A new version is out[ Download ](https://github.com/mukul500/AnimeXStream/releases/tag/v0.4.0) .That fixes all issues, Update your app to the latest version
