### ISSUE TITLE
Layout issue

### ISSUE THREAD

**Issue by DemonRem** [mukul500/AnimeXStream#40]
i install the application from apk , however as i launch the application the search button is on the favorite button, i dont know if its help but i using hawhii p30 any idea what to do?

**Comment by crazyuploader** [comment]
> i install the application from apk , however as i launch the application the search button is on the favorite button, i dont know if its help but i using hawhii p30 any idea what to do?

It'd be better if you could attach a screenshot of it

**Comment by DemonRem** [comment]
![Screenshot_20200501_191126_net xblacky animexstream](https://user-images.githubusercontent.com/29927382/80820501-a460da00-8bdf-11ea-931b-0a83217a8939.jpg)

**Comment by mukul500** [comment]
A new version is out[ Download ](https://github.com/mukul500/AnimeXStream/releases/tag/v0.4.0) .That fixes all issues, Update your app to the latest version
