### ISSUE TITLE
Certain anime not playing and has only 1080p quality

### ISSUE THREAD

**Issue by AKASHGHISH** [mukul500/AnimeXStream#400]

**Comment by Axe090** [comment]
By the dev: "Gogoanime encyrpted all urls, will take time to fix" 
Wait patiently until fixed.

**Comment by mukul500** [comment]
A new version is out[ Download ](https://github.com/mukul500/AnimeXStream/releases/tag/v0.4.0) .That fixes all issues, Update your app to the latest version
