### ISSUE TITLE
This app now unattended 

### ISSUE THREAD

**Issue by 3008dead** [mukul500/AnimeXStream#404]
![IMG_20211226_170120](https://user-images.githubusercontent.com/77578650/147406663-c362658d-98ab-430b-8914-9a556fe3d42b.jpg)

Use or find any other app . Developer had left this app ...🥲

**Comment by 3008dead** [comment]
http://github.com/justdvnsh/AnimeClassroom

Herse the link in mail

**Comment by mukul500** [comment]
A new version is out[ Download ](https://github.com/mukul500/AnimeXStream/releases/tag/v0.4.0) .That fixes all issues, Update your app to the latest version
