### ISSUE TITLE
App is not working

### ISSUE THREAD

**Issue by Luffy-naruto** [mukul500/AnimeXStream#405]
Videos are not playing whenever I go to any videos it shows only pause button

**Comment by Axe090** [comment]
By the dev: "Gogoanime encyrpted all urls, will take time to fix" 
Wait patiently until fixed.

**Comment by kl3jvi** [comment]
check out my app https://github.com/kl3jvi/animity

**Comment by mukul500** [comment]
A new version is out[ Download ](https://github.com/mukul500/AnimeXStream/releases/tag/v0.4.0) .That fixes all issues, Update your app to the latest version
