### ISSUE TITLE
Videos aren't playing......just a black screen


### ISSUE THREAD

**Issue by ITADORI-15** [mukul500/AnimeXStream#407]
Plz fix it asap

**Comment by Axe090** [comment]
By the dev: "Gogoanime encyrpted all urls, will take time to fix" 
Wait patiently until fixed.

**Comment by ITADORI-15** [comment]
Yeah! Thanx bro

**Comment by mukul500** [comment]
A new version is out[ Download ](https://github.com/mukul500/AnimeXStream/releases/tag/v0.4.0) .That fixes all issues, Update your app to the latest version
