### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by theapache64** [mukul500/AnimeXStream#41]
Awesome design. I've implemented the design in of my project.

![](https://github.com/theapache64/topcorn/raw/master/extras/light.png)
![](https://github.com/theapache64/topcorn/raw/master/extras/dark.png)

Looking forward for your feedback :)

![image](https://user-images.githubusercontent.com/9678279/80431477-2a92cd00-890f-11ea-90de-17cd46c3e521.png)

https://github.com/theapache64/topcorn

**Comment by mukul500** [comment]
Keep it up man

**Comment by mukul500** [comment]
Contact ne on facebook, or any social media

**Comment by theapache64** [comment]
Can you ping me @ https://t.me/theapache64 ?
