### ISSUE TITLE
Can you please fix this

### ISSUE THREAD

**Issue by Aaron2481** [mukul500/AnimeXStream#411]
When I try to watch something the video player just goes black no play button and sometimes it says i have no internet even tho I do

**Comment by skully-coder** [comment]
Facing the same issue

**Comment by mukul500** [comment]
Dude this time issue is Big and might require some time to fix. So please be patient

**Comment by Fruelund** [comment]
Same here

**Comment by KitigayaKirito** [comment]
Please try to fix ut fast

**Comment by Axe090** [comment]
> Please try to fix ut fast 

Are you paying him?!! Wait until it gets fixed don't keep asking the same thing over and over

**Comment by KitigayaKirito** [comment]
> fixed

No bro

**Comment by KitigayaKirito** [comment]
> > Please try to fix ut fast
> 
> Are you paying him?!! Wait until it gets fixed, don't keep asking the same thing over and over

No bro

**Comment by KitigayaKirito** [comment]
I am waiting 😁😁

**Comment by mukul500** [comment]
A new version is out[ Download ](https://github.com/mukul500/AnimeXStream/releases/tag/v0.4.0) .That fixes all issues, Update your app to the latest version
