### ISSUE TITLE
"Gogoanime encyrpted all urls, will take time to fix" 

### ISSUE THREAD

**Issue by Axe090** [mukul500/AnimeXStream#413]
By the dev: "Gogoanime encyrpted all urls, will take time to fix"
Wait patiently until fixed and don't open anymore issues on this. The dev will update the app as soon as it's fixed!

**Comment by 3008dead** [comment]
Who is Dev ?

**Comment by Axe090** [comment]
> Who is Dev ?

mukul500

**Comment by Just-A-Random-Idiot** [comment]
How long do you think it will take?

**Comment by GU9T** [comment]
How long do you think it'll take to fix

**Comment by Axe090** [comment]
> How long do you think it'll take to fix

As long as it takes the dev to fix it.... So stop asking! as I said before the app will be updated once fixed.

**Comment by GU9T** [comment]
You don't have to be an asshole its been a little over a week now. Just asking a sinple question. your acting like we are telling to dec to hurry the hell up. Geez

**Comment by Axe090** [comment]
> You don't have to be an asshole its been a little over a week now. Just asking a sinple question. your acting like we are telling to dec to hurry the hell up. Geez

Not being an asshole. The dev told me to inform you guys to wait so that you stop openning useless issues and keep asking for etas. And it's the same question over and over! and you asking it won't make the dev fix/uodate the app faster. so wait like everyone else! If that's such a problem then go find a different app,

**Comment by GU9T** [comment]
You act like people just can't ask questions. Some people might have not seen what you said so they are gonna ask. You should deliver your message better and stop being vague about it. Most people want etas with everything.  You act like we are rushimg the dev

**Comment by Axe090** [comment]
> You act like people just can't ask questions. Some people might have not seen what you said so they are gonna ask. You should deliver your message better and stop being vague about it. Most people want etas with everything.  You act like we are rushimg the dev

If you're not rushing the dev why would you keep asking how long it would take, have some common sense! The message I wrote above is very self explanatory. You're the only one I'm seeing complaining. Again there's no point in asking again and again as that wouldn't make a difference! Get that thtough your thick skull. I'm done arguing with you. Either wait or gtfo.

**Comment by GU9T** [comment]
I literally asked one fuckin time shithead calm down 1 question cant hurt anyone im not opening new issues or anything 1 question can't hurt anyone. And answering the question would stop everyone else from asking.  Your the one being the asshole

**Comment by Axe090** [comment]
"> I literally asked one fuckin time shithead calm down 1 question cant hurt anyone im not opening new issues or anything 1 question can't hurt anyone. And answering the question would stop everyone else from asking. Your the one being the asshole

I already replied you above "As long as it takes the dev to fix it.... So stop asking! as I said before the app will be updated once fixed." now you're the one who started arguing after it. My message was clear enough and if you can't see that the kudos!

**Comment by GU9T** [comment]
Again very vauge answers arent good answers

**Comment by Axe090** [comment]
> Again very vauge answers arent good answers

What part of as long as it takes the dev to fix it you're not understanding is beyond me. It's not about being vague. have you done any coding, tried getting over unencrypted url's? Guessing not. Even the dev can't give an eta. Once he finds a way to circumvent the recent change he'll update the app now is that clear enough?!

**Comment by Axe090** [comment]
Also he has a life and these are holidays the app is'nt his main priority, so give him some space to figure it out. He isn't abandoning the app.

**Comment by LordOfDawns** [comment]
> Also he has a life and these are holidays the app isn't his main priority, give him some space to figure it out. He isn't abandoning the app.

How can he take this long time to fix this app bruh he has responsibility to fullfill off, since this many peoples are issuing atleast he should post a text about the concerned issue, this makes everyone look like dev doesn't even know that app isn't working.

**Comment by LordOfDawns** [comment]
> Also he has a life and these are holidays the app isn't his main priority, give him some space to figure it out. He isn't abandoning the app.

How can he take this long time to fix this app bruh he has responsibility to fullfill off, since this many peoples are issuing atleast he should post a text about the concerned issue, this makes everyone look like dev doesn't even know that app isn't working :/

**Comment by LordOfDawns** [comment]
> Also he has a life and these are holidays the app isn't his main priority, give him some space to figure it out. He isn't abandoning the app.

How can he take this long time to fix this app bruh he has responsibility to fullfill off, since this many peoples are issuing atleast he should post a text letting us know that he's working on the concerned issue, this makes everyone look like dev doesn't even know that app isn't working :/

**Comment by Axe090** [comment]
> > Also he has a life and these are holidays the app isn't his main priority, give him some space to figure it out. He isn't abandoning the app.
> 
> How can he take this long time to fix this app bruh he has responsibility to fullfill off, since this many peoples are issuing atleast he should post a text letting us know that he's working on the concerned issue, this makes everyone look like dev doesn't even know that app isn't working :/

https://github.com/mukul500/AnimeXStream/issues/396#issuecomment-1001904152
He has already replied about this before! And obviously he knows about the error! First of all it's not his responsibility, are you fucking paying him?! If he wants he can never fix the app and you can't fucking do anything! Secondly I've already made this post here on his instructions which states it'll take time to fix. And you're saying (that how does it take this long to fix the app) do you know more or does the dev? so get the fuck off your high horse! Either wait or fix it yourself or gtfo! People like you are the reasons why he doesn't engage with you!

**Comment by LordOfDawns** [comment]
> > > Also he has a life and these are holidays the app isn't his main priority, give him some space to figure it out. He isn't abandoning the app.
> > 
> > 
> > How can he take this long time to fix this app bruh he has responsibility to fullfill off, since this many peoples are issuing atleast he should post a text letting us know that he's working on the concerned issue, this makes everyone look like dev doesn't even know that app isn't working :/
> 
> [#396 (comment)](https://github.com/mukul500/AnimeXStream/issues/396#issuecomment-1001904152) He has already replied about this before! And obviously he knows about the error! First of all it's not his responsibility, are you fucking paying him?! If he wants he can never fix the app and you can't fucking do anything! Secondly I've already made this post here on his instructions which states it'll take time to fix. And you're saying (that how does it take this long to fix the app) do you know more or does the dev? so get off your high horse! Either wait or fix it yourself or gtfo! People like you are the reason why he doesn't engage here.!

Well I love your app and can't find any better anime streaming app than yours since I'm using it in my T.v to watch with my brother, because of the error issue we were unable to watch anime, tried sites struggling with ads but after 2 weeks of waiting the app wasn't fixed and I felt frustrated, like me many people may have different types of problems you can't think off.... Even tho am not paying to dev, it's a Devs responsibility to fix his application asap, the quote "with great power comes the great responsibility" is what am trying to say here. Ik the app will be fixed someday and I didn't meant any disrespect in this or previous reply, hope you understand me and will stop replying rudely considering how soft I'm talking

**Comment by Axe090** [comment]
> > > > Also he has a life and these are holidays the app isn't his main priority, give him some space to figure it out. He isn't abandoning the app.
> > > 
> > > 
> > > How can he take this long time to fix this app bruh he has responsibility to fullfill off, since this many peoples are issuing atleast he should post a text letting us know that he's working on the concerned issue, this makes everyone look like dev doesn't even know that app isn't working :/
> > 
> > 
> > [#396 (comment)](https://github.com/mukul500/AnimeXStream/issues/396#issuecomment-1001904152) He has already replied about this before! And obviously he knows about the error! First of all it's not his responsibility, are you fucking paying him?! If he wants he can never fix the app and you can't fucking do anything! Secondly I've already made this post here on his instructions which states it'll take time to fix. And you're saying (that how does it take this long to fix the app) do you know more or does the dev? so get off your high horse! Either wait or fix it yourself or gtfo! People like you are the reason why he doesn't engage here.!
> 
> Well I love your app and can't find any better anime streaming app than yours since I'm using it in my T.v to watch with my brother, because of the error issue we were unable to watch anime, tried sites struggling with ads but after 2 weeks of waiting the app wasn't fixed and I felt frustrated, like me many people may have different types of problems you can't think off.... Even tho am not paying to dev, it's a Devs responsibility to fix his application asap, the quote "with great power comes the great responsibility" is what am trying to say here. Ik the app will be fixed someday and I didn't meant any disrespect in this or previous reply, hope you understand me and will stop replying rudely considering how soft I'm talking

it's not about your "soft replies" that pisses me or the dev. It's your thinking that you can demand shit even after being constantly told that the dev will update the app once fixed. Again it's not his responsibility! what if he never fixes the app no one can do anything about it. If he want's he can just delete the whole repo. The dev told me himself it's cause of people constantly demanding he doesn't feel like working on it! If I'm rude then so be it if it makes you stop making these posts!

**Comment by Axe090** [comment]
> > > > Also he has a life and these are holidays the app isn't his main priority, give him some space to figure it out. He isn't abandoning the app.
> > > 
> > > 
> > > How can he take this long time to fix this app bruh he has responsibility to fullfill off, since this many peoples are issuing atleast he should post a text letting us know that he's working on the concerned issue, this makes everyone look like dev doesn't even know that app isn't working :/
> > 
> > 
> > [#396 (comment)](https://github.com/mukul500/AnimeXStream/issues/396#issuecomment-1001904152) He has already replied about this before! And obviously he knows about the error! First of all it's not his responsibility, are you fucking paying him?! If he wants he can never fix the app and you can't fucking do anything! Secondly I've already made this post here on his instructions which states it'll take time to fix. And you're saying (that how does it take this long to fix the app) do you know more or does the dev? so get off your high horse! Either wait or fix it yourself or gtfo! People like you are the reason why he doesn't engage here.!
> 
> Well I love your app and can't find any better anime streaming app than yours since I'm using it in my T.v to watch with my brother, because of the error issue we were unable to watch anime, tried sites struggling with ads but after 2 weeks of waiting the app wasn't fixed and I felt frustrated, like me many people may have different types of problems you can't think off.... Even tho am not paying to dev, it's a Devs responsibility to fix his application asap, the quote "with great power comes the great responsibility" is what am trying to say here. Ik the app will be fixed someday and I didn't meant any disrespect in this or previous reply, hope you understand me and will stop replying rudely considering how soft I'm talking

The world won't end if the app isn't fixed the way you're making it seem it's such a big responsibility. And if you know that the app will get fixed one day then why are you asking how long is it taking! I get you're frustrated but have you thought about the dev or what he might be going through?! There are other options out there if you can't wait. Just stop demanding an eta!

**Comment by Axe090** [comment]
> > > > Also he has a life and these are holidays the app isn't his main priority, give him some space to figure it out. He isn't abandoning the app.
> > > 
> > > 
> > > How can he take this long time to fix this app bruh he has responsibility to fullfill off, since this many peoples are issuing atleast he should post a text letting us know that he's working on the concerned issue, this makes everyone look like dev doesn't even know that app isn't working :/
> > 
> > 
> > [#396 (comment)](https://github.com/mukul500/AnimeXStream/issues/396#issuecomment-1001904152) He has already replied about this before! And obviously he knows about the error! First of all it's not his responsibility, are you fucking paying him?! If he wants he can never fix the app and you can't fucking do anything! Secondly I've already made this post here on his instructions which states it'll take time to fix. And you're saying (that how does it take this long to fix the app) do you know more or does the dev? so get off your high horse! Either wait or fix it yourself or gtfo! People like you are the reason why he doesn't engage here.!
> 
> Well I love your app and can't find any better anime streaming app than yours since I'm using it in my T.v to watch with my brother, because of the error issue we were unable to watch anime, tried sites struggling with ads but after 2 weeks of waiting the app wasn't fixed and I felt frustrated, like me many people may have different types of problems you can't think off.... Even tho am not paying to dev, it's a Devs responsibility to fix his application asap, the quote "with great power comes the great responsibility" is what am trying to say here. Ik the app will be fixed someday and I didn't meant any disrespect in this or previous reply, hope you understand me and will stop replying rudely considering how soft I'm talking

The world won't end if the app isn't fixed the way you're making it seem it's such a big responsibility. And if you know that the app will get fixed one day then why are you asking how long is it taking! I get you're frustrated but have you thought about the dev or what he might be going through?! There are other options out there if you can't wait.The dev told me himself it's cause of people constantly demanding he doesn't feel like working on it! Just stop demanding an eta. Yes I was rude cos you were coming off as being entitled! and how is not being able to watch anime without ads such a big problem LMAO!

**Comment by ITADORI-15** [comment]
Bro @Axe090 is it actually possible 2 fix the app?
If the URLs are encrypted.....how do u get info from there.
Just a random question popped in my brain...

**Comment by Axe090** [comment]
> Bro @Axe090 is it actually possible 2 fix the app? If the URLs are encrypted.....how do u get info from there. Just a random question popped in my brain...

Someone has sort of already figured it out (won't say here) the dev is trying to see if a similar fix can be implemented in his app. Hopefully he's able to fix it soon.

**Comment by ITADORI-15** [comment]
Ok bro thnx

**Comment by manrhansetia** [comment]
Is it done yet ?

**Comment by ITADORI-15** [comment]
Bro u can use other websites also ryt ....is it tat only gogoanime is gud
Even zoro is good ryt....

**Comment by mukul500** [comment]
A new version is out[ Download ](https://github.com/mukul500/AnimeXStream/releases/tag/v0.4.0) .That fixes all issues, Update your app to the latest version
