### ISSUE TITLE
Unable to install 

### ISSUE THREAD

**Issue by Dewet-sa** [mukul500/AnimeXStream#414]
Am unable to install the all the downloadable apk files even though I ve already deleted the previous version app that was installed  before beginning the new version installation

**Comment by mukul500** [comment]
A new version is out[ Download ](https://github.com/mukul500/AnimeXStream/releases/tag/v0.4.0) .That fixes all issues, Update your app to the latest version

**Comment by Dewet-sa** [comment]
🙏 Thank you for your hard work
