### ISSUE TITLE
Video playback issue

### ISSUE THREAD

**Issue by The-BOT-says** [mukul500/AnimeXStream#417]
Your app is working fine but when I try to play video in it, it doesn't open or what should I say that the video is not starting

**Comment by Axe090** [comment]
Read this: https://github.com/mukul500/AnimeXStream/issues/413
and close the issue!

**Comment by Steve0528** [comment]
AXE090-if you know anything about this app is there a huge update coming?

**Comment by Steve0528** [comment]
I think there is because the video is not starting at all

**Comment by Steve0528** [comment]
Axe090-don't be mad at the comments because yeah I understand them because I'm one of them too, we know that the developer will update it soon.

**Comment by Axe090** [comment]
> Axe090-don't be mad at the comments because yeah I understand them because I'm one of them too, we know that the developer will update it soon.

Bro if you know then wait. It is up to the dev when he's able to fix it and push an update. Can't give an eta.

**Comment by Steve0528** [comment]
There your angry again hahaha

**Comment by Axe090** [comment]
> There your angry again hahaha

Not angry just straight.

**Comment by kl3jvi** [comment]
check out my app https://github.com/kl3jvi/animity

**Comment by mukul500** [comment]
A new version is out[ Download ](https://github.com/mukul500/AnimeXStream/releases/tag/v0.4.0) .That fixes all issues, Update your app to the latest version
