### ISSUE TITLE
How much we have to wait...? 😔😔

### ISSUE THREAD

**Issue by Guddu77788888** [mukul500/AnimeXStream#418]

**Comment by Axe090** [comment]
> 

Seriously what's wrong with you?! Do you not know what waiting patiently means??? Are you paying the dev? Stop opening useless issues. This will not make the dev fix/update the app any faster! Have some patience!!!!

**Comment by Steve0528** [comment]
I'm sorry but can you fix this before january 9 because theres a new season coming
"I'm just asking!!"

**Comment by Axe090** [comment]
> I'm sorry but can you fix this before january 9 because theres a new season coming
> "I'm just asking!!"
> 

We're all waiting (including me) the dev hasn't given an eta as he's still working on it, rest assured the update will come if/when he's able to fix it.

**Comment by riimuru** [comment]
> > I'm sorry but can you fix this before january 9 because theres a new season coming
> > "I'm just asking!!"
> 
> We're all waiting (including me) the dev hasn't given an eta as he's still working on it, rest assured the update will come if/when he's able to fix it.

Since gogoanime changed streaming servers, I'm sure it'll take some time.

**Comment by kl3jvi** [comment]
check out my app https://github.com/kl3jvi/animity

**Comment by mukul500** [comment]
A new version is out[ Download ](https://github.com/mukul500/AnimeXStream/releases/tag/v0.4.0) .That fixes all issues, Update your app to the latest version
