### ISSUE TITLE
Issue with wifi connection 

### ISSUE THREAD

**Issue by HarshaKosuru** [mukul500/AnimeXStream#42]
Video plays good with mobile reception but when ever I connected to my wifi it show no connection retry. Is this for me or everyone facing the same issue?

**Comment by GoluLiliput** [comment]
It's ur specific bug bro

**Comment by mukul500** [comment]
A new version is out[ Download ](https://github.com/mukul500/AnimeXStream/releases/tag/v0.4.0) .That fixes all issues, Update your app to the latest version
