### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by RYUkenji123** [mukul500/AnimeXStream#420]
Video isn't playing

**Comment by Axe090** [comment]
> Video isn't playing

https://github.com/mukul500/AnimeXStream/issues/413

**Comment by ElezeoraDraconius** [comment]
> Video isn't playing

Did you not read previous post you dumb dumb??

**Comment by PainUzumaki** [comment]
> Video isn't playing

You don't read Dev post you fool you fool 😂

**Comment by Axe090** [comment]
https://github.com/mukul500/AnimeXStream/issues/438

**Comment by mukul500** [comment]
A new version is out[ Download ](https://github.com/mukul500/AnimeXStream/releases/tag/v0.4.0) .That fixes all issues, Update your app to the latest version
