### ISSUE TITLE
Anime x stream

### ISSUE THREAD

**Issue by GABIlopez** [mukul500/AnimeXStream#421]
![Screenshot_20220111-235654_Anime X Stream.jpg](https://user-images.githubusercontent.com/32043783/149055947-c786762d-3e86-4157-adbd-3e627dbb9e2e.jpg)

**Comment by Axe090** [comment]
Read this: https://github.com/mukul500/AnimeXStream/issues/413

Also the dev is busy and will look at the app after 15th.

**Comment by DuyBowlisgood** [comment]
The video didn't play 😌😥 fix it, please. Thank you.

**Comment by GABIlopez** [comment]
https://9anime.vc/

**Comment by GABIlopez** [comment]
https://zoro.to/home

**Comment by GABIlopez** [comment]
https://www1.animeyt.live/

https://animeyt.moe/#.XgqTFNCoZSE.messenger

https://animeyt.to/

https://ytanime.tv/

https://animeyt.es/

**Comment by GABIlopez** [comment]
https://anime-flv.net/

https://ww3.animeflv.cc/

https://www3.animeflv.net/

**Comment by GABIlopez** [comment]
https://ww2.gogoanimes.org/

https://www3.gogoanime.cm/

https://gogoanime.mom/

https://ww1.gogoanime2.org/

https://gogoanime.nl/home

**Comment by GABIlopez** [comment]
https://9anime.movie/

https://9anime.me/

https://9anime.se/

https://9anime.click/

https://9animes.pro/

https://9anime.surf/

https://ww.9animes.org/

https://ww.9anime2.com/

https://9anime.gg/

**Comment by GABIlopez** [comment]
https://animeflv.ac/ver-jkanime-online-gratis-en-hd

https://jk-anime.net/

https://www5.jkanime.video/

https://jkanime.top/

https://jkanime.net/

**Comment by Axe090** [comment]
@GABIlopez we get it bro. You know about the index.

**Comment by kl3jvi** [comment]
> @GABIlopez we get it bro, you know about the index.

use this https://github.com/kl3jvi/animity

**Comment by GABIlopez** [comment]
![Screenshot_20220121-001452_Animity.jpg](https://user-images.githubusercontent.com/32043783/150459825-bc582ebb-64bd-4f20-8516-19ef6eda6fca.jpg)

**Comment by Fruelund** [comment]
> > @GABIlopez we get it bro, you know about the index.
> 
> use this https://github.com/kl3jvi/animity

Thanks mate

**Comment by ITADORI-15** [comment]
Kayuri
Tako Play
Cloudstream
Animity
The 4 best apps I personally use

**Comment by Fruelund** [comment]
Thanks.

Tako Play's .apk is broken, currently. But will keep an eye on a fix.

Another app that seems to work is Saikou. Aniyomi is also OK.

**Comment by ITADORI-15** [comment]
@Fruelund 
Bro there is nothing wrong with tako play

**Comment by ITADORI-15** [comment]
I am using it currently

**Comment by Fruelund** [comment]
The .apk is broken. The app won't install. It gives a parsing error. Others have reported the same issue. 
👇
![Screenshot_20220124-075453_Package installer.jpg](https://user-images.githubusercontent.com/90288058/150738697-fe731fe1-9f60-49d7-9820-07770434d294.jpg)

**Comment by Fruelund** [comment]
Since you already installed it, it doesn't affect you.

**Comment by ITADORI-15** [comment]
Bro just open your file explorer and in the downloads section find the app and then install.
Plz confirm after tat

**Comment by ITADORI-15** [comment]
Tats what I did

**Comment by ITADORI-15** [comment]
And also I really thank you for the Saikou app
❤

**Comment by Fruelund** [comment]
You're welcome 👍

Even if I try installing the apk from files, I get the same error. 

https://user-images.githubusercontent.com/90288058/150739947-aba84717-c0e9-4e82-b374-8f23cfdfd378.mp4

**Comment by Fruelund** [comment]
It's also a bit strange that the apk is just named "app.apk"

**Comment by ITADORI-15** [comment]
So sry for making u try but yeah

**Comment by Fruelund** [comment]
No worries. The dev is aware of the problem and is fixing it.

**Comment by ITADORI-15** [comment]
Dude 2 be honest it's working lemme show u
https://user-images.githubusercontent.com/83289685/150745290-ff267017-8dea-4cf8-9aaf-250bac45ac2d.mp4

**Comment by Fruelund** [comment]
Well it's not working for me, as you can see in my video. 

I'm wondering if it's a compatability issue, because the other guy who reported the same problem has the same phone I do. Samsung Galaxy S21.

All the other apps I got from github installed with no issues. Only this one gives the parsing error.

I'll wait and see what the dev comes up with. 

https://user-images.githubusercontent.com/90288058/150746341-8f4ee91d-bd2b-4b71-9955-76694d03d236.mp4

**Comment by ITADORI-15** [comment]
Ohhh ok.
What if u use SAI app to install 
Split Apk Installer.
It might work
But its upto u

**Comment by Fruelund** [comment]
Was worth a try. But no go. 

https://user-images.githubusercontent.com/90288058/150747343-3f5dde54-969c-4325-a0a8-668fbf9d503b.mp4

**Comment by ITADORI-15** [comment]
Tough luck ....let's wait for dev's reply then.
Thnx once again for saikou app

**Comment by Fruelund** [comment]
You're welcome. And thanks for trying 🙂👍

**Comment by kl3jvi** [comment]
use my app guys https://github.com/kl3jvi/animity

**Comment by Fruelund** [comment]
Using it 👍

**Comment by ITADORI-15** [comment]
> use my app guys https://github.com/kl3jvi/animity

Broo How can we not use your app
It's amazing

**Comment by ITADORI-15** [comment]
> You're welcome. And thanks for trying 🙂👍

Wish I could help🤓

**Comment by ITADORI-15** [comment]
@Fruelund 
Bro are u able to use the saikou app ....with the anilist login
Its crashing for me

**Comment by Fruelund** [comment]
Yeah, works fine for me. Is the whole app crashing for you?

**Comment by ITADORI-15** [comment]
Yeah only when I login 2 anilist

**Comment by Fruelund** [comment]
I'm logged in with AniList and it works perfectly.

Have you tried logging out of AniList and then logging in through Saikou?

**Comment by ITADORI-15** [comment]
So I found the problem ig 
First with the acc logged in the app started crashing,then when I logged out and tried again it was working perfectly fine 
Then later I tried using a diff acc ,.it is working perfectly fine
So the prob was with the first anilist acc
Now its resolved

**Comment by Axe090** [comment]
https://github.com/mukul500/AnimeXStream/issues/438

**Comment by mukul500** [comment]
A new version is out[ Download ](https://github.com/mukul500/AnimeXStream/releases/tag/v0.4.0) .That fixes all issues, Update your app to the latest version

**Comment by GABIlopez** [comment]
https://github.com/mukul500/AnimeXStream/releases/download/v0.4.0/AnimexStream-v0.4.0-arm64-v8a-release.apk

**Comment by GABIlopez** [comment]
App

**Comment by GABIlopez** [comment]
Anime x stream no app

**Comment by GABIlopez** [comment]
![Screenshot_20220402-121025_Settings.jpg](https://user-images.githubusercontent.com/32043783/161389556-937b435f-81ae-4ea4-97d2-140b6082ac65.jpg)
