### ISSUE TITLE
Bug/glitch

### ISSUE THREAD

**Issue by Naofuminal** [mukul500/AnimeXStream#422]
Sir I'm using this app since 8-10 months, and this is one the best app I've ever used but rn I'm facing an issue, I'm not able to play any videos since last 20-25 days. I'm really waiting for a long time please can you solve this quickly? Thank you so much for making such a great app!

**Comment by Axe090** [comment]
Read this: https://github.com/mukul500/AnimeXStream/issues/413

Also the dev is busy and will look at the app after 15th.

**Comment by Naofuminal** [comment]
Yeah that's understandable, thank you for reply

**Comment by Naofuminal** [comment]
I think we should

**Comment by Axe090** [comment]
> So shall we delete this app? It hasn't worked in months

Go ahead, no need to inform here 😂

**Comment by Axe090** [comment]
> I think we should

K

**Comment by Naofuminal** [comment]
> 

*Wait

**Comment by Naofuminal** [comment]
> > I think we should
> 
> K

Wait a minute 😶 who are you 😂

**Comment by Axe090** [comment]
> > > I think we should
> > 
> > K
> 
> Wait a minute 😶 who are you 😂

No one you need to know about. Just leave

**Comment by Naofuminal** [comment]
> > > > I think we should
> > > 
> > > 
> > > K
> > 
> > 
> > Wait a minute 😶 who are you 😂
> 
> No one you need to know about. Just leave

Hi it's 15 January today so is he free now?

**Comment by Fruelund** [comment]
Dude, just use Aniyomi or CloudStream. They work fine, most of the time. 

But I hope this app will be fixed eventually, because there's a shortage of alternatives.

However, the guy who does it isn't getting paid. He does it for free. So we have no right to make unreasonable demands. Let him get around to it in his own time.

**Comment by Naofuminal** [comment]
> Dude, just use Aniyomi or CloudStream. They work fine, most of the time.
> 
> But I hope this app will be fixed eventually, because there's a shortage of alternatives.
> 
> However, the guy who does it isn't getting paid. He does it for free. So we have no right to make unreasonable demands. Let him get around to it in his own time.

Yeah ik he isn't getting paid, i wasn't really making demands though I was requesting him

**Comment by ITADORI-15** [comment]
Aniyomi has a preview version also....try using tat also

**Comment by razwatsup** [comment]
> Aniyomi has a preview version also....try using tat also

Tat? 

İf one thing animextream being down was usefull is the alt apps listed in the messages. Someone should do a list :)

Btw why you say prevıew aniyomi is paid?

**Comment by Naofuminal** [comment]
> > So shall we delete this app? It hasn't worked in months
> 
> Go ahead, no need to in

**Comment by Axe090** [comment]
> > Aniyomi has a preview version also....try using tat also
> 
> Tat? 
> 
> İf one thing animextream being down was usefull is the alt apps listed in the messages. Someone should do a list :)
> 
> Btw why you say prevıew aniyomi is paid?

Visit piracy.moe for more stuff

**Comment by ITADORI-15** [comment]
😏😏😏😏
