### ISSUE TITLE
Y dont u guys use this alternative......until AnimeXstream Is fixed

### ISSUE THREAD

**Issue by ITADORI-15** [mukul500/AnimeXStream#423]
https://github.com/kaungsatthe1n/Tako-Play

**Comment by RYUkenji123** [comment]
This app is slow

**Comment by ITADORI-15** [comment]
Oh is it so
😅

**Comment by kl3jvi** [comment]
use this https://github.com/kl3jvi/animity

**Comment by mukul500** [comment]
A new version is out[ Download ](https://github.com/mukul500/AnimeXStream/releases/tag/v0.4.0) .That fixes all issues, Update your app to the latest version
