### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by Naofuminal** [mukul500/AnimeXStream#424]
As axe said dev will start looking at app after 15 and It's 17 January, so has he started his work yet?

**Comment by kl3jvi** [comment]
> As axe said dev will start looking at app after 15 and It's 17 January, so has he started his work yet?

check out my app https://github.com/kl3jvi/animity

**Comment by Naofuminal** [comment]
> > As axe said dev will start looking at app after 15 and It's 17 January, so has he started his work yet?
> 
> check out my app https://github.com/kl3jvi/animity

How can I download your app?

**Comment by kl3jvi** [comment]
@Naofuminal https://github.com/kl3jvi/animity/releases

**Comment by Naofuminal** [comment]
> @Naofuminal https://github.com/kl3jvi/animity/releases

Your app is working great but can you please add 480p and 720p quality option?

**Comment by kl3jvi** [comment]
> > @Naofuminal https://github.com/kl3jvi/animity/releases
> 
> Your app is working great but can you please add 480p and 720p quality option?

My app fetches the best quality possible per episode

**Comment by Naofuminal** [comment]
> @Naofuminal https://github.com/kl3jvi/animity/releases



> > > @Naofuminal https://github.com/kl3jvi/animity/releases
> > 
> > 
> > Your app is working great but can you please add 480p and 720p quality option?
> 
> My app fetches the best quality possible per episode

I'm not using wifi, I've limited internet so i can't use your app I'm sorry. But I'd love to use your app if i could watch in 480/720p

**Comment by navrjar** [comment]
https://github.com/kaungsatthe1n/Tako-Play
I suggest this app bro , You can choose Resolution.

**Comment by Naofuminal** [comment]
> https://github.com/kaungsatthe1n/Tako-Play I suggest this app bro , You can choose Resolution.

Thank you soo much <3

**Comment by 3008dead** [comment]
> > > @Naofuminal https://github.com/kl3jvi/animity/releases
> > 
> > 
> > Your app is working great but can you please add 480p and 720p quality option?
> 
> My app fetches the best quality possible per episode

Bro you r well versed in kotlin . Can't you fix this app ?

**Comment by Axe090** [comment]
https://github.com/mukul500/AnimeXStream/issues/438

**Comment by mukul500** [comment]
A new version is out[ Download ](https://github.com/mukul500/AnimeXStream/releases/tag/v0.4.0) .That fixes all issues, Update your app to the latest version
