### ISSUE TITLE
Time for fixing

### ISSUE THREAD

**Issue by 3008dead** [mukul500/AnimeXStream#425]
I heard that you will look into app after 15 . So can we say that by the end of Jan we can use your app like we used to ? 

Please say something to it ....

**Comment by TREYAKSH** [comment]
Ok

**Comment by Axe090** [comment]
https://github.com/mukul500/AnimeXStream/issues/435

**Comment by Axe090** [comment]
https://github.com/mukul500/AnimeXStream/issues/438

**Comment by mukul500** [comment]
A new version is out[ Download ](https://github.com/mukul500/AnimeXStream/releases/tag/v0.4.0) .That fixes all issues, Update your app to the latest version
