### ISSUE TITLE
Bro plz take our request into consideration and repair the app

### ISSUE THREAD

**Issue by ITADORI-15** [mukul500/AnimeXStream#426]
We have been waiting for a month now.
So please try to work on this app.

**Comment by Axe090** [comment]
> We have been waiting for a month now.
> So please try to work on this app.

Use alts, the app will be fixed when it's fixed.

**Comment by Axe090** [comment]
https://github.com/mukul500/AnimeXStream/issues/435

**Comment by Axe090** [comment]
https://github.com/mukul500/AnimeXStream/issues/438

**Comment by mukul500** [comment]
A new version is out[ Download ](https://github.com/mukul500/AnimeXStream/releases/tag/v0.4.0) .That fixes all issues, Update your app to the latest version
