### ISSUE TITLE
Use this for now

### ISSUE THREAD

**Issue by kira910** [mukul500/AnimeXStream#427]
Use this until animexstream is fixed

https://github.com/Killerpac/Kayuri

**Comment by 3008dead** [comment]
![Screenshot_2022-01-20-10-09-02-52_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/77578650/150274528-dd3c2ed4-81be-4c26-8086-8d52916aa8ae.jpg)

Which apk to download ?

**Comment by ITADORI-15** [comment]
Usually universal release bro

**Comment by ITADORI-15** [comment]
The 11 mb one

**Comment by ITADORI-15** [comment]
Thnx bro @kira910

**Comment by kira910** [comment]
Its the universal release and your welcome 😁

**Comment by vikd-94** [comment]
Thank you sooooo much for this ❤️

**Comment by mukul500** [comment]
A new version is out[ Download ](https://github.com/mukul500/AnimeXStream/releases/tag/v0.4.0) .That fixes all issues, Update your app to the latest version
