### ISSUE TITLE
Anime doesn't play

### ISSUE THREAD

**Issue by GoluLiliput** [mukul500/AnimeXStream#428]
Anime doesn't play. Please fix!

**Comment by ElezeoraDraconius** [comment]
AniMe dOeSn't PlAy. PleAsE FiX!

**Comment by ElezeoraDraconius** [comment]
> Anime doesn't play. Please fix!

AniMe dOeSn't PlAy. PleAsE FiX!

**Comment by Ijustwanndedede** [comment]
The new update make me can't watch any anime video please fix it tq:')

**Comment by kl3jvi** [comment]
I suggest to use my app https://github.com/kl3jvi/animity

**Comment by GoluLiliput** [comment]
> I suggest to use my app https://github.com/kl3jvi/animity

It doesn't work too. Says timeout.

**Comment by faizm1243** [comment]
Anime doesn't play, Pls fix...

**Comment by Axe090** [comment]
https://github.com/mukul500/AnimeXStream/issues/438

**Comment by mukul500** [comment]
A new version is out[ Download ](https://github.com/mukul500/AnimeXStream/releases/tag/v0.4.0) .That fixes all issues, Update your app to the latest version
