### ISSUE TITLE
Almost a month 

### ISSUE THREAD

**Issue by JS7803** [mukul500/AnimeXStream#429]
Time to fix this app, almost 28 days past and now there are no update. Im tired to fix it now. I recommend to those want to watch an anime in apk download cloudstream

**Comment by whghjyh** [comment]
you can use the app called kayuri,These two APPs are very similar.

**Comment by 3008dead** [comment]
> you can use the app called kayuri,These two APPs are very similar.

Bro kayuri is also using same server . But why only this app is facing problem ?

**Comment by JS7803** [comment]
> 

Can  you give me a link?

**Comment by navrjar** [comment]
I suggest to use this app before he fixed.
https://github.com/kaungsatthe1n/Tako-Play

**Comment by kl3jvi** [comment]
I suggest to use my app https://github.com/kl3jvi/animity @navrjar @3008dead @whghjyh @JS7803

**Comment by 3008dead** [comment]
> I suggest to use this app before he fixed. https://github.com/kaungsatthe1n/Tako-Play

Bro using different app is not problem. Problem is that why only this app is not running while all other app are running properly

**Comment by Axe090** [comment]
https://github.com/mukul500/AnimeXStream/issues/435

**Comment by Axe090** [comment]
https://github.com/mukul500/AnimeXStream/issues/438

**Comment by mukul500** [comment]
A new version is out[ Download ](https://github.com/mukul500/AnimeXStream/releases/tag/v0.4.0) .That fixes all issues, Update your app to the latest version
