### ISSUE TITLE
[Suggestion] Add manual dark mode toggle

### ISSUE THREAD

**Issue by BT-Dub** [mukul500/AnimeXStream#43]
I think it would be pretty useful to have a manual dark mode toggle so that devices where there is no system dark mode option/ the system dark mode does not effect the app, can access the app's dark mode.

**Comment by Flaxms** [comment]
I agree, i would love to have this feature. And maybe add a timed dark mode aswell.

**Comment by mukul500** [comment]
Please see #76 for app suggestions
