### ISSUE TITLE
App not working when i Play anime

### ISSUE THREAD

**Issue by Sudip909** [mukul500/AnimeXStream#431]
How much time tack to fix it, please  fix it as soon as possible , i wash dav doing great but long time i am not seeing anime so please 😞😞

**Comment by Axe090** [comment]
https://github.com/mukul500/AnimeXStream/issues/435

**Comment by Axe090** [comment]
https://github.com/mukul500/AnimeXStream/issues/438

**Comment by mukul500** [comment]
A new version is out[ Download ](https://github.com/mukul500/AnimeXStream/releases/tag/v0.4.0) .That fixes all issues, Update your app to the latest version
