### ISSUE TITLE
Can u suggest apps like for animexstream for movies and series
Adless and good ui


### ISSUE THREAD

**Issue by ITADORI-15** [mukul500/AnimeXStream#432]

**Comment by ElezeoraDraconius** [comment]
.

**Comment by soymadip** [comment]
Momix, Cinehub

**Comment by SkAfif** [comment]
Anime Fanz Tube

**Comment by mukul500** [comment]
A new version is out[ Download ](https://github.com/mukul500/AnimeXStream/releases/tag/v0.4.0) .That fixes all issues, Update your app to latest version
