### ISSUE TITLE
Not Working Since Last November

### ISSUE THREAD

**Issue by fal3n-4ngel** [mukul500/AnimeXStream#434]
Well app is facing some server side error, probably fetching data from the site..

**Comment by Axe090** [comment]
https://github.com/mukul500/AnimeXStream/issues/435

**Comment by Axe090** [comment]
https://github.com/mukul500/AnimeXStream/issues/435

**Comment by Axe090** [comment]
https://github.com/mukul500/AnimeXStream/issues/438

**Comment by mukul500** [comment]
A new version is out[ Download ](https://github.com/mukul500/AnimeXStream/releases/tag/v0.4.0) .That fixes all issues, Update your app to latest version
