### ISSUE TITLE
Dev Update

### ISSUE THREAD

**Issue by Axe090** [mukul500/AnimeXStream#435]
By the Dev (mukul500):

"I have decrypted all media urls" 

"Just need to find a way to fool gogoanime that media is playing from their website"

"It  will be fixed in 2-3 days maximum" 

Hopefully

**Comment by ITADORI-15** [comment]
Manh thanks a lott❤❤❤

**Comment by 3008dead** [comment]
Thnx for updating us bro....✌️✌️

**Comment by Xenonyxes** [comment]
Thank you ur app is awesome and I hope to keep using it.

**Comment by mukul500** [comment]
A new version is out[ Download ](https://github.com/mukul500/AnimeXStream/releases/tag/v0.4.0) .That fixes all issues, Update your app to latest version
