### ISSUE TITLE
Not loding anime

### ISSUE THREAD

**Issue by belugacat858** [mukul500/AnimeXStream#437]
When I start an anime episode the episode does not load even if I click on next episode 
And it shows priveous episode on first episode
![Screenshot_2022-01-31-20-14-46-276_net xblacky animexstream](https://user-images.githubusercontent.com/98756640/151814235-7daef64f-84f8-4196-bb6d-db6214a82228.jpg)

**Comment by ITADORI-15** [comment]
Bro refer #435

**Comment by Axe090** [comment]
https://github.com/mukul500/AnimeXStream/issues/438

**Comment by mukul500** [comment]
A new version is out[ Download ](https://github.com/mukul500/AnimeXStream/releases/tag/v0.4.0) .That fixes all issues, Update your app to latest version
