### ISSUE TITLE
Dev Update 2

### ISSUE THREAD

**Issue by Axe090** [mukul500/AnimeXStream#438]
By dev (mukul500):

"Anime is playing now"

Things to do before finalizing update:
"Need to update section for quality" 
"Need to refactor old code, so it can be mantained"
"Resolve Buffering issue"

The dev will soon update the app, it might take some more time for the finishing touches. He's taking time off work this week
 to fix it, so be grateful and wait patiently.

App will be back up soon :)

**Comment by Edisontheking10** [comment]
I dont know to do that I am confused I will just wait for the new update

**Comment by Axe090** [comment]
> I dont know to do that I am confused I will just wait for the new update

You don't need to do anything. The dev is, so yes just wait for the update.

**Comment by mukul500** [comment]
A new version is out[ Download ](https://github.com/mukul500/AnimeXStream/releases/tag/v0.4.0) .That fixes all issues, Update your app to latest version
