### ISSUE TITLE
4.0 Crashes

### ISSUE THREAD

**Issue by Warillusen** [mukul500/AnimeXStream#439]
Clicking on an anime crashes the app and clicking on a video still doesn't play.

**Comment by mukul500** [comment]
If you are having trouble complete reinstallation of app will work fine

**Comment by Warillusen** [comment]
Unfortunately all versions do the same thing even on a fresh install.

**Comment by mukul500** [comment]
Will look into issue and provide new update

**Comment by Warillusen** [comment]
It seems to have been fixed.
