### ISSUE TITLE
[SUGGESTION]Animepahe as source instead of gogoanime

### ISSUE THREAD

**Issue by AyushJ2002** [mukul500/AnimeXStream#44]
Better quality 
Less size 
Animepahe.com

Maybe ??

**Comment by GoluLiliput** [comment]
I think the developper has thought pretty good in terms of the source. Animepahe only offers anime in 720p and 1080p qualities which is little inconvenient for all the users in terms of data restrictions. Many anime in the present source that the dev has used are also available in 720p and 1080p including lower resolutions. If the feauture comes up in future where multiple sources are used, it would be amazing but in the initial phase implementation, I feel the scraper used is thoughtful and sensible

**Comment by AyushJ2002** [comment]
No I get it. I said that just because even though animepahe provides 720p and 1080p it's sizes are small , like around 100 - 150 mb for 720p which is almost equal to 480p on gogoanime . Hence even for data restricted people  they could enjoy good quality content on small sizes. 
Anyhow you have done an amazing job 
So far the best
