### ISSUE TITLE
Unrecognized token

### ISSUE THREAD

**Issue by TuupacFR** [mukul500/AnimeXStream#445]
![IMG_20220209_215918](https://user-images.githubusercontent.com/99209812/153261716-10d7ee47-c227-44c4-b088-0126642812b2.jpg)

When I want to resume watching a show, I have this screen on my Android TV.

**Comment by mukul500** [comment]
Make sure u have installed the correct app. Because the error doesn't look like it is from my app. Maybe you have installed a fork

**Comment by ITADORI-15** [comment]
That kinda looks like cloudstream
