### ISSUE TITLE
Add more features

### ISSUE THREAD

**Issue by Bungeexgum** [mukul500/AnimeXStream#446]
Add a Settings.

Option to hide Dub and Chinese Anime.

 Add a feature in search bar where we can Search or Filter by Genre/Popularity/Score. Like any other site/app do.

When we selected an anime there should be a Related stuff and Recommended. So we know that there's a Prequel/Sequel. Like any other site/app do.

Add Anilist or Mal. Like any other site/app do

I don't even know why this repo has many stars when there are many features missing. Plus the home ui Atleast put an effort to change it, it's so obvious that it's gogo base.

**Comment by mukul500** [comment]
No. it is what it is. If you wanna use it, Use. don't boss here

**Comment by ITADORI-15** [comment]
This app is actually known for its simplicity....I found it gud only

**Comment by Bungeexgum** [comment]
> This app is actually known for its simplicity....I found it gud only

Bruh it's not simplicity, it's inconvenience, It's no different from Cloudstream 3, Synopsis is the only info. These kind of app is the worst

**Comment by Aaron2481** [comment]
Then go watch those if you dont like this app so much or better yet make your own app
