### ISSUE TITLE
Dark mode not working+ Feature Request

### ISSUE THREAD

**Issue by Tanay2804** [mukul500/AnimeXStream#454]
Hi Mukul and team! 
-I just downloaded this application and found that the dark mode feature is not working for my S10 Plus Phone..so I think it's better to have a toggle for it in the app..rather than have the system do it. 
-Also Can we please have an option to delete/ View our History or the anime we saw recently..? 
This app is very very good and I hope to see many more improvements in the future. Thanks a lot!!!

**Comment by Tanay2804** [comment]
Please reply or fix the issue...

**Comment by ITADORI-15** [comment]
The dark mode is working perfectly for me...![Screenshot_20220217-125738_Anime X Stream.jpg](https://user-images.githubusercontent.com/83289685/154426267-5632b09e-bfeb-44e4-ae8e-a812aa911f2d.jpg)
Device samsung m30
