### ISSUE TITLE
Force keyboard opening and few more subtle bugs and suggestion

### ISSUE THREAD

**Issue by GoluLiliput** [mukul500/AnimeXStream#46]
Whenever we click on the search anime, the keyboard opens which is completely fine. But the keyboard persists even when we have opened any anime from the search result page, where it is completely unnecessary. Please update the setting such that the keyboard opens only when we touch the text box there we are supposed to type the anime's name or episode number(in future updates perhaps, this feature might come) in the anime detail page.

Also please remove out the curve border overlay from the PIP mode. It's super cool though in the main full-screen mode⭐

And just if possible, please add some more sources as scrapers so that we may have more playback resolution qualities. Also it would b neat if the res. quality are named as 360p, 480p, 720p, 1080p and so on.

**Comment by frytkisasmaczne** [comment]
for me keyboard closes when i press enter

**Comment by mukul500** [comment]
A new version is out[ Download ](https://github.com/mukul500/AnimeXStream/releases/tag/v0.4.0) .That fixes all issues, Update your app to the latest version
