### ISSUE TITLE
 GogoAnime Changed the Urls Scheme Will Wait For The Saturday to see if it reverts back or will you push an update

### ISSUE THREAD

**Issue by Dvixe** [mukul500/AnimeXStream#462]

**Comment by mukul500** [comment]
They have changed back to the old URL scheme. I think they might revert back to newer version again

**Comment by 3008dead** [comment]
If they don't go back then would we get an update for app ?

**Comment by Aftabyasir9** [comment]
> If they don't go back then would we get an update for app ?

I think then just using the previous version of app will make do

**Comment by 3008dead** [comment]
> I think then just using the previous version of app will make do

Then tell me when to use old version off app
