### ISSUE TITLE
Is the older version of app working or not ?

### ISSUE THREAD

**Issue by 3008dead** [mukul500/AnimeXStream#468]

**Comment by ayushman-ray** [comment]
I don't think so. I tried reverting back to the older version, only to face the same issue.

**Comment by ITADORI-15** [comment]
![Screenshot_20220227-110116_Anime X Stream.jpg](https://user-images.githubusercontent.com/83289685/155869556-c96e4225-1f31-4422-85ed-3b0e17db7c94.jpg)

**Comment by STARGAMERMJ** [comment]
> I don't think so. I tried reverting back to the older version, only to face the same issue.

Use the Kayuri application. This app's developer already fixed the problem.
