### ISSUE TITLE
Movies hang at play button, Episodes don't

### ISSUE THREAD

**Issue by Giv0** [mukul500/AnimeXStream#47]
Ive been going through Konosuba! recently and when trying to watch Legend of Crimson it hangs at the play button on a black screen.  It doesn't load, but the progress bar and ui are there but unscaled to fit the screen.  Might be an internet issue, but all the other episodes worked fine. I also have a internet data monitor, and when trying to play it it shows no download or upload activity, which means it isn't even trying.

**Comment by shoukolate** [comment]
Actually gogoanime servers suck, it's probably not app's fault

**Comment by Giv0** [comment]
I was gonna try crunchyroll, but I'm like yeah no ads please

**Comment by GoluLiliput** [comment]
> I was gonna try crunchyroll, but I'm like yeah no ads please

Crunchyroll is ssly bullshit. U find only a handful of anime there. U can get patched crunchy apk on internet if u are interested

**Comment by Giv0** [comment]
I don't know why I didn't think about that.  Free no ads is better than free + ads

**Comment by mukul500** [comment]
A new version is out[ Download ](https://github.com/mukul500/AnimeXStream/releases/tag/v0.4.0) .That fixes all issues, Update your app to the latest version
