### ISSUE TITLE
Player not working

### ISSUE THREAD

**Issue by sarada993** [mukul500/AnimeXStream#478]
When i installed the latest version,it worked for few days flawlessly....then one day the player stopped working.... although it opens but no loading,no buffering, nothing..... Just black screen....i used to watch in this app.... but this thing is a Problem.... please fix this.

**Comment by trk20** [comment]
Same issue here, hope it's not too big of a fix, really like this app.

**Comment by mukul500** [comment]
App has been fixed. Please [Download](https://github.com/mukul500/AnimeXStream/releases/tag/v0.5.0) it from release section. Make sure to clean install it.
