### ISSUE TITLE
Player broke again! 😞

### ISSUE THREAD

**Issue by Theroumag** [mukul500/AnimeXStream#479]
The app has stopped loading videos like last time! This has to be a recent change to because I was watching Attack on Titan today, and when I came back for the next episode it broke :/. Other animes don't load either. Please fix 🙏 this is by far the best anime app

**Comment by SkAfif** [comment]
https://anonfiles.com/r4E796Q2x0/Anime_Fanz_Tube_v1.3.3_mod_apkdone.com_1_apk
Use this app. It's BETTER. No, I am not it's promoter. I just have great experience with it

**Comment by ITADORI-15** [comment]
Use saikou or kayuri or animity😁

**Comment by Theroumag** [comment]
> https://anonfiles.com/r4E796Q2x0/Anime_Fanz_Tube_v1.3.3_mod_apkdone.com_1_apk Use this app. It's BETTER. No, I am not it's promoter. I just have great experience with it

If you want me to download something post a GitHub link I'm not downloading your random app 😶

**Comment by Theroumag** [comment]
> Use saikou or kayuri or animity😁

I've been using Saikou and it works but I prefer my clean interface and favorites tab 😔

**Comment by mukul500** [comment]
App has been fixed. Please [Download](https://github.com/mukul500/AnimeXStream/releases/tag/v0.5.0) it from release section. Make sure to clean install it.
