### ISSUE TITLE
Cant search any titles on App

### ISSUE THREAD

**Issue by BlackoftheDawn** [mukul500/AnimeXStream#482]
I've been trying to search titles and play videos since around 12am this morning and neither has been possible which is odd because around 10pm last night the app was working just fine.

**Comment by SkAfif** [comment]
> I've been trying to search titles and play videos since around 12am this morning and neither has been possible which is odd because around 10pm last night the app was working just fine.

https://anonfiles.com/r4E796Q2x0/Anime_Fanz_Tube_v1.3.3_mod_apkdone.com_1_apk
Use this app. It's BETTER. No, I am not it's promoter. I just have great experience with it

**Comment by mukul500** [comment]
App has been fixed. Please [Download](https://github.com/mukul500/AnimeXStream/releases/tag/v0.5.0) it from release section. Make sure to clean install it.
