### ISSUE TITLE
Not playing video

### ISSUE THREAD

**Issue by RubaasKhan** [mukul500/AnimeXStream#484]
Player doesn't load the video checked other anime too nothing is playing

**Comment by Lavish883** [comment]
@RubaasKhan We have been waiting for a long time so I decided to just make one myself. And here I finished yesterday. Here is the link to my app https://github.com/Lavish883/lokiStreamLite I tried to recreate as closely as possible

**Comment by mukul500** [comment]
App has been fixed. Please [Download](https://github.com/mukul500/AnimeXStream/releases/tag/v0.5.0) it from release section. Make sure to clean install it.
