### ISSUE TITLE
App isn't playing anime again

### ISSUE THREAD

**Issue by Manniga** [mukul500/AnimeXStream#485]
At first most of the anime on the app were saying and some weren't but now none of them (or none that i have saved) are working.

Hope you fix the whole issue :)

**Comment by Lavish883** [comment]
@Manniga We have been waiting for a long time so I decided to just make one myself. And here I finished yesterday. Here is the link to my app https://github.com/Lavish883/lokiStreamLite I tried to recreate as closely as possible

**Comment by mukul500** [comment]
App has been fixed. Please [Download](https://github.com/mukul500/AnimeXStream/releases/tag/v0.5.0) it from release section. Make sure to clean install it.
