### ISSUE TITLE
Videos not playing again

### ISSUE THREAD

**Issue by TGSLotus** [mukul500/AnimeXStream#487]
Just an idea is there anyway to put on a progressive control over the servers like a fail safe operation. Meaning that it will try to regenerate connections when there are noticeable server errors. Or even try to connect to other servers. Seems like the reoccurring problem is mostly encountered on the servers changing secured shakes causing the app to fail playing any video.
Or much better having back up servers to simultaneously reconnect when one connection is down.

**Comment by STARGAMERMJ** [comment]
> Just an idea is there anyway to put on a progressive control over the servers like a fail safe operation. Meaning that it will try to regenerate connections when there are noticeable server errors. Or even try to connect to other servers. Seems like the reoccurring problem is mostly encountered on the servers changing secured shakes causing the app to fail playing any video. Or much better having back up servers to simultaneously reconnect when one connection is down.

Use this app:- https://github.com/ScriptHelper/AversHenni

**Comment by mukul500** [comment]
App has been fixed. Please [Download](https://github.com/mukul500/AnimeXStream/releases/tag/v0.5.0) it from release section. Make sure to clean install it.
