### ISSUE TITLE
Video won't load

### ISSUE THREAD

**Issue by AyReptile** [mukul500/AnimeXStream#489]
Video won't load after selecting an anime, Loading wheel appears for a second then play button appears, if pressed it disappears and nothing happens, time just displays 00:00 and doesn't change. Video quality selector does open the menu but there are no options to select from. 

Tried fresh install and didn't seem to fix any issues, rest of UI like Playback speed seems to be working.

**Comment by junaid1563** [comment]
Yeah Same issue I am facing. Tried installing universal version but same issue.

**Comment by Dragon9445** [comment]
Yes it's happening with me too

**Comment by STARGAMERMJ** [comment]
> Video won't load after selecting an anime, Loading wheel appears for a second then play button appears, if pressed it disappears and nothing happens, time just displays 00:00 and doesn't change. Video quality selector does open the menu but there are no options to select from.
> 
> Tried fresh install and didn't seem to fix any issues, rest of UI like Playback speed seems to be working.

Use this app:- https://github.com/ScriptHelper/AversHenni

**Comment by Lavish883** [comment]
@AyReptile @junaid1563 @Dragon9445 We have been waiting for a long time so I decided to just make one myself. And here I finished yesterday. Here is the link to my app https://github.com/Lavish883/lokiStreamLite I tried to recreate as closely as possible

**Comment by mukul500** [comment]
App has been fixed. Please [Download](https://github.com/mukul500/AnimeXStream/releases/tag/v0.5.0) it from release section. Make sure to clean install it.
