### ISSUE TITLE
Videos not loading still

### ISSUE THREAD

**Issue by Draxeman** [mukul500/AnimeXStream#491]

**Comment by RealRoboKnight** [comment]
It's still not working.

**Comment by STARGAMERMJ** [comment]
> _No description provided._

Use this app:- https://github.com/ScriptHelper/AversHenni

**Comment by STARGAMERMJ** [comment]
> Same for me.

Use this app:- https://github.com/ScriptHelper/AversHenni

**Comment by Lavish883** [comment]
@Draxeman @literallypan @RealRoboKnight We have been waiting for a long time so I decided to just make one myself. And here I finished yesterday. Here is the link to my app https://github.com/Lavish883/lokiStreamLite I tried to recreate as closely as possible

**Comment by mukul500** [comment]
App has been fixed. Please [Download](https://github.com/mukul500/AnimeXStream/releases/tag/v0.5.0) it from release section. Make sure to clean install it.
