### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by Fruelund** [mukul500/AnimeXStream#492]
This app is always so broken. Nothing can play.

**Comment by STARGAMERMJ** [comment]
> This app is always so broken. Nothing can play.

Use this app:- https://github.com/ScriptHelper/AversHenni

**Comment by Lavish883** [comment]
@Fruelund  We have been waiting for a long time so I decided to just make one myself. And here I finished yesterday. Here is the link to my app https://github.com/Lavish883/lokiStreamLite I tried to recreate as closely as possible #507

**Comment by Fruelund** [comment]
Nice. Thanks

**Comment by mukul500** [comment]
App has been fixed. Please [Download](https://github.com/mukul500/AnimeXStream/releases/tag/v0.5.0) it from release section. Make sure to clean install it.
