### ISSUE TITLE
Yep. Still, not working.

### ISSUE THREAD

**Issue by literallypan** [mukul500/AnimeXStream#494]
It's been months since this app won't play any videos.

**Comment by ITADORI-15** [comment]
Use Saikou till then

**Comment by 3008dead** [comment]
> Use Saikou till then

Send link to download

**Comment by ITADORI-15** [comment]
https://github.com/saikou-app/saikou/releases/tag/v1.1.6

**Comment by STARGAMERMJ** [comment]
> > Use Saikou till then
> 
> Send link to download
Use this app
https://github.com/ScriptHelper/AversHenni

**Comment by STARGAMERMJ** [comment]
> It's been months since this app won't play any videos.

Use this app:- https://github.com/ScriptHelper/AversHenni

**Comment by kl3jvi** [comment]
Use my app instead [Animity App](https://github.com/kl3jvi/animity)

**Comment by Lavish883** [comment]
@literallypan @3008dead

**Comment by mukul500** [comment]
App has been fixed. Please [Download](https://github.com/mukul500/AnimeXStream/releases/tag/v0.5.0) it from release section. Make sure to clean install it.
