### ISSUE TITLE
Not playing any episode of any anime 

### ISSUE THREAD

**Issue by LeoTMG** [mukul500/AnimeXStream#497]
I try to watch a anime and i click the play button and nothing the play button dissappears and just a black screen

Can you fix or tell me how to fix it

**Comment by kentonyodo** [comment]
How to fix the video not playing issue

**Comment by kl3jvi** [comment]
@LeoTMG @kentonyodo Use my app [Animity App](https://github.com/kl3jvi/animity)

**Comment by Lavish883** [comment]
@LeoTMG @kentonyodo We have been waiting for a long time so I decided to just make one myself. And here I finished yesterday. Here is the link to my app https://github.com/Lavish883/lokiStreamLite I tried to recreate as closely as possible

**Comment by BeastKing3** [comment]
Thanks man 🔥🔥 it's the same as anime x stream

**Comment by mukul500** [comment]
App has been fixed. Please [Download](https://github.com/mukul500/AnimeXStream/releases/tag/v0.5.0) it from release section. Make sure to clean install it.
