### ISSUE TITLE
Video not playing and vary buffer 

### ISSUE THREAD

**Issue by Sudip909** [mukul500/AnimeXStream#498]
Fix the problem as soon as possible, i am unable to watch anime 🤧🤧🤧 , video not playing with large buffer 🤧

**Comment by kl3jvi** [comment]
@Sudip909 @ShavonHastings Use my app [Animity App](https://github.com/kl3jvi/animity)

**Comment by Lavish883** [comment]
@Sudip909 @ShavonHastings  We have been waiting for a long time so I decided to just make one myself. And here I finished yesterday. Here is the link to my app https://github.com/Lavish883/lokiStreamLite I tried to recreate as closely as possible.

**Comment by Sudip909** [comment]
Ok thanks, can you give me your original apk loki streem link??? 🙂

**Comment by Lavish883** [comment]
> Ok thanks, can you give me your original apk loki streem link??? 🙂

@Sudip909  The original loki stream app is also made by me but it stopped working and i made it two years ago so the code was bad. So i just decided to just make one from scratch. The new one is better either way. https://github.com/Lavish883/lokiStreamLite

**Comment by mukul500** [comment]
App has been fixed. Please [Download](https://github.com/mukul500/AnimeXStream/releases/tag/v0.5.0) it from release section. Make sure to clean install it.
