### ISSUE TITLE
Video not playing

### ISSUE THREAD

**Issue by GoluLiliput** [mukul500/AnimeXStream#499]
The anime video is not playing, guess it needs server change. Please fix the app. This was my mainstream app to watch anime🥺🥺

**Comment by Lavish883** [comment]
@GoluLiliput We have been waiting for a long time so I decided to just make one myself. And here I finished yesterday. Here is the link to my app https://github.com/Lavish883/lokiStreamLite I tried to recreate as closely as possible

**Comment by GoluLiliput** [comment]
> @GoluLiliput We have been waiting for a long time so I decided to just make one myself. And here I finished yesterday. Here is the link to my app https://github.com/Lavish883/lokiStreamLite I tried to recreate as closely as possible

I love the app. Could use some UI upgrade or something. But the app is super handy and useful. Also can u make it so that when any video is played, it opens up in landscape view?

**Comment by Lavish883** [comment]
> > @GoluLiliput We have been waiting for a long time so I decided to just make one myself. And here I finished yesterday. Here is the link to my app https://github.com/Lavish883/lokiStreamLite I tried to recreate as closely as possible
> 
> I love the app. Could use some UI upgrade or something. But the app is super handy and useful. Also can u make it so that when any video is played, it opens up in landscape view?

Thx I am glad u found it helpful, Okay I will make it when any video plays it opens landscape view. There is also a full screen button u can click on the player. Let me know what u mean by ui upgrade specifically. So I can make it best for the users. (I am pretty bad ui design)

**Comment by GoluLiliput** [comment]
> > > @GoluLiliput We have been waiting for a long time so I decided to just make one myself. And here I finished yesterday. Here is the link to my app https://github.com/Lavish883/lokiStreamLite I tried to recreate as closely as possible
> > 
> > I love the app. Could use some UI upgrade or something. But the app is super handy and useful. Also can u make it so that when any video is played, it opens up in landscape view?
> 
> Thx I am glad u found it helpful, Okay I will make it when any video plays it opens landscape view. There is also a full screen button u can click on the player. Let me know what u mean by ui upgrade specifically. So I can make it best for the users. (I am pretty bad ui design)

By UI, u can take reference from Kayuri Anime app. It was made out of animeXstream too. It's on github

**Comment by Lavish883** [comment]
> > > > @GoluLiliput We have been waiting for a long time so I decided to just make one myself. And here I finished yesterday. Here is the link to my app https://github.com/Lavish883/lokiStreamLite I tried to recreate as closely as possible
> > > 
> > > 
> > > I love the app. Could use some UI upgrade or something. But the app is super handy and useful. Also can u make it so that when any video is played, it opens up in landscape view?
> > 
> > 
> > Thx I am glad u found it helpful, Okay I will make it when any video plays it opens landscape view. There is also a full screen button u can click on the player. Let me know what u mean by ui upgrade specifically. So I can make it best for the users. (I am pretty bad ui design)
> 
> By UI, u can take reference from Kayuri Anime app. It was made out of animeXstream too. It's on github

Okay thx so much I will take a look and update it.

**Comment by mukul500** [comment]
App has been fixed. Please [Download](https://github.com/mukul500/AnimeXStream/releases/tag/v0.5.0) it from release section. Make sure to clean install it.
