### ISSUE TITLE
Put the app on F-Droid

### ISSUE THREAD

**Issue by fffelix-jan** [mukul500/AnimeXStream#5]
Although it would not be possible to put such an app on the Play Store, I think F-Droid would be a good home for the app. A similar app for watching YouTube, NewPipe, is also there.

**Comment by mukul500** [comment]
I think it's not possible to put this app on fdroid because we are using Firebase Crashlytics. Fdroid policies don't allow apps that are using Google services

**Comment by fffelix-jan** [comment]
Since Firebase Crashlytics is some form of Google tracking which affects the user's privacy, may it please be removed then? Then the app would be Google-free and somewhat more private.

**Comment by mukul500** [comment]
It is used to check crashes. Firebase database is used to check updates and provide notifications for newer updates. Is there any alternative for all those ?

**Comment by fffelix-jan** [comment]
The F-Droid store checks for updates on its own, so the user can go to a central location to update all of their open-source apps.

**Comment by surajmandalcell** [comment]
F-droid allows piracy related app?

**Comment by shoukolate** [comment]
If it's not possible to publish app to F-Droid, you can even publish on XDA-Labs. They allow such apps.

**Comment by mukul500** [comment]
Ok i will publish it to xda labs

**Comment by roshavagarga** [comment]
@mukul500 ACRA is the open-source alternative to Firebase. Moving to that would make the app truly foss :)

**Comment by shoukolate** [comment]
@roshavagarga Can you please give a link to ACRA?

**Comment by roshavagarga** [comment]
https://github.com/ACRA/acra

**Comment by linsui** [comment]
I can patch out the firebase deps in F-Droid build metadata. Could I package it for F-Droid?
