### ISSUE TITLE
This is the best app existing on earth fix this soon anime x stream 10k people are waiting 😁

### ISSUE THREAD

**Issue by Bootylicker12345** [mukul500/AnimeXStream#502]
Pls fix this soon this is the best app existing on earth I'll be waiting anime x stream 😁

**Comment by Lavish883** [comment]
We have been waiting for a long time so I decided to just make one myself. And here I finished yesterday.  Here is the link to my app https://github.com/Lavish883/lokiStreamLite  I tried to recreate as closely as possible

**Comment by mukul500** [comment]
After watching all the request, I decided to revive this project.  It will be back soon

**Comment by mukul500** [comment]
App has been fixed. Please [Download](https://github.com/mukul500/AnimeXStream/releases/tag/v0.5.0) it from release section. Make sure to clean install it.

**Comment by Bootylicker12345** [comment]
Bro thank you I can finally use it

**Comment by Bootylicker12345** [comment]
IT WORKS THANK YOU SO MUCH YOU
R THE BEST KEEP IT GOING MY BRO 🔥🔥🔥

**Comment by Bootylicker12345** [comment]
I CAN'T STOP THANKING YOU WEBSITES CAN'T EVEN SURVIVE WITHOUT BRINGING YOU
TO ANOTHER TAB THANKS THANKS THANKS THANKS THANKS THANKS THANKS
🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥

**Comment by Bootylicker12345** [comment]
I have an issue I hope you don't mind to fix it every time I fast forward
it lags and crashes my phone hope you don't mind if you fix it ❤😁
