### ISSUE TITLE
Add a tv version of app

### ISSUE THREAD

**Issue by Gamergurl31** [mukul500/AnimeXStream#503]
I would like to know if there can be a tv version of app. is this open source ?
 I would like to know how to make this a tv app.
Or if u know could u send a tutorial?

**Comment by Hecker0711** [comment]
THIS.

**Comment by Gamergurl31** [comment]
I don't understand 😕

**Comment by mukul500** [comment]
App has been fixed. Please [Download](https://github.com/mukul500/AnimeXStream/releases/tag/v0.5.0) it from release section. Make sure to clean install it.
