### ISSUE TITLE
Video is not playing 

### ISSUE THREAD

**Issue by stark-cpu** [mukul500/AnimeXStream#504]
![Screenshot_2022-08-05-02-26-11-184_net xblacky animexstream](https://user-images.githubusercontent.com/90656285/182951485-c107a8b8-b604-4930-b633-e06e4d0c1bb9.png)

**Comment by Lavish883** [comment]
@stark-cpu  
We have been waiting for a long time so I decided to just make one myself. And here I finished yesterday. Here is the link to my app https://github.com/Lavish883/lokiStreamLite I tried to recreate as closely as possible

**Comment by ROLHISHIOUS** [comment]
Same, doesn't work

**Comment by Lavish883** [comment]
> Same, doesn't work

@ROLHISHIOUS try this one https://github.com/Lavish883/LokiStream-Lite

**Comment by voXrey** [comment]
Same

**Comment by mukul500** [comment]
App has been fixed. Please [Download](https://github.com/mukul500/AnimeXStream/releases/tag/v0.5.0) it from release section. Make sure to clean install it.
