### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by Hellwolf666** [mukul500/AnimeXStream#508]
When i click on some episode for example 75 on one piece there is only black screen any ideas?

**Comment by Lavish883** [comment]
@Hellwolf666 this app doesnt work any more the owner is fixing it in the meantime use this https://github.com/Lavish883/LokiStream-Lite

**Comment by mukul500** [comment]
App has been fixed. Please [Download](https://github.com/mukul500/AnimeXStream/releases/tag/v0.5.0) it from release section. Make sure to clean install it.
