### ISSUE TITLE
Development?

### ISSUE THREAD

**Issue by GoluLiliput** [mukul500/AnimeXStream#51]
This app is all hyped up all around the discord and reddits, even the r/anime-piracy recognises this app as the number. 1 app for watching anime. But is this app still in development? I am curious if the developer is still active. It's long since an update

**Comment by mukul500** [comment]
I have been busy in some office works. In my free time playing LOL a lot. So wasn't focused on this. I will try to implement Sync feature in upcoming update.

**Comment by GoluLiliput** [comment]
Sir please develop this app further and don't leave it hanging. U have no idea how popular this app has become in the Otaku and anime community on reddit.

**Comment by mukul500** [comment]
Seriously this app is that popular ? I can see only 6k user using this app. So I wasn't interested it to further develop because of low users.

**Comment by GoluLiliput** [comment]
The anime-piracy mod is a huge community and it recommends only 4 to 5 apps best for anime and manga on iOS and Android... The AnimeXStream app is listed on number 1. Followed by it are app like AnimeGlare, AnYme X and one more... Manga app are tachiyomi . I don't remember all. But yes sir, your app is very favoured app. 
Please create a discord server if possible. If its difficult for u to manage, me and my Bois will manage it for ya. We will be server's moderators

**Comment by mukul500** [comment]
Contact me on my social media.

**Comment by GoluLiliput** [comment]
How can I contact you?

**Comment by mukul500** [comment]
https://www.facebook.com/xblackyy

**Comment by GoluLiliput** [comment]
M there.. I added u

**Comment by kljaja** [comment]
i would like to help in any way possible too, so can you also bring me into the "helpers" team, i mean this app has great potential and that's why i would love to help too

**Comment by Matterhorn56** [comment]
it is no longer number one
ngl the new number one is very smooth, with a nice ui
im not saying it here since that really wouldnt be fair to mukul500

**Comment by mukul500** [comment]
I am having a hard time with life. So I can't complete any request of yours. If you find any better solution you can switch to them. Its your personal preference. 

Thankyou

**Comment by Matterhorn56** [comment]
i hope you get through whatever it is u are going through

**Comment by mukul500** [comment]
A new version is out[ Download ](https://github.com/mukul500/AnimeXStream/releases/tag/v0.4.0) .That fixes all issues, Update your app to the latest version
