### ISSUE TITLE
Crash on OnePlus 6T

### ISSUE THREAD

**Issue by Civetz0** [mukul500/AnimeXStream#53]
I was using the app normally yesterday but this morning I couldn't open it without crashes. I'm on Op6T_O2_beta_35 and using "AnimexStream-v0.2.0-armeabi-v7a-release" this version of the app. It crashes as soon as I open it but it loads up the main page, I can try clearing the memory and see if that solves the issue
![Screenshot_20200603-120354](https://user-images.githubusercontent.com/66361806/83623990-59e1cd00-a592-11ea-9039-f29b9a440b95.jpg)
Edit
I tried clearing the memory, reinstalling the same and all the other versions but nothing worked. It just keep crashing no matter what.

**Comment by Supermuskox** [comment]
Same issue on the OnePlus 6 with _AnimexStream-v0.2.0-arm64-v8a-release.apk_ and _OxygenOS 10.3.3_. 

Worked yesterday, but crashes on startup. As the person above me has described, the main page loads, although not with pictures for me, but right after that it crashes. Clearing cache and clearing storage of the app has no effect.

**Comment by samurailook** [comment]
Same issue on samsung s10e,
Worked fine yesterday but started crashing since this morning.

**Comment by crazyuploader** [comment]
It's not just you guys, it's crashing for some reason

**Comment by Praj77** [comment]
Same crash issue on redmi 7

**Comment by berri10010** [comment]
I'm having the same issue on my OnePlus 6T.

**Comment by Superblazer** [comment]
Same

**Comment by aramo44** [comment]
same on mi 9 xiaomi everything was fine till yesterday
![Screenshot_2020-06-03-18-45-08-113_com miui bugreport](https://user-images.githubusercontent.com/12279629/83658133-74d03380-a5ca-11ea-94b9-4285f2eebd76.png)

**Comment by crazyuploader** [comment]
> same on mi 9 xiaomi everything was fine till yesterday
> ![Screenshot_2020-06-03-18-45-08-113_com miui bugreport](https://user-images.githubusercontent.com/12279629/83658133-74d03380-a5ca-11ea-94b9-4285f2eebd76.png)

That's what I got here as well

**Comment by withmytech** [comment]
I can confirm this as well. I spent like an hour fixing it. Changed my Custom ROM like 3 times. Might be a server issue or an App issue for it to be crashing.

**Comment by harshal-99** [comment]
Yep same on Redmi Note 5 Pro

**Comment by Superblazer** [comment]
It's fixed, he released a new update now

**Comment by berri10010** [comment]
I was just about to say that. Works just fine now.👍
