### ISSUE TITLE
App not running ! Google-services.json file missing ! ( App debug )

### ISSUE THREAD

**Issue by justdvnsh** [mukul500/AnimeXStream#58]
I had to open this issue, since I was not able to find any mailing list or channel  , thus created this issue.

After building the app, when the app is to run, it fails.

**Comment by crazyuploader** [comment]
You'll first need to generate `google-services.json` from [here](https://firebase.google.com/) and place it in your project.

**Comment by justdvnsh** [comment]
Yup. Got it working. Thanks !
