### ISSUE TITLE
[SUGGESTION] Option to increase play speed

### ISSUE THREAD

**Issue by Dighvijay** [mukul500/AnimeXStream#59]
Great job with the app, it would be much better if there is an option to increase the play speed as anime tends to be a tad slower than other shows/movies.

**Comment by justdvnsh** [comment]
https://github.com/mukul500/AnimeXStream/pull/64

**Comment by Dighvijay** [comment]
That's brilliant! Thanks!

**Comment by mukul500** [comment]
A new version is out[ Download ](https://github.com/mukul500/AnimeXStream/releases/tag/v0.4.0) .That fixes all issues, Update your app to the latest version
