### ISSUE TITLE
No internet bug

### ISSUE THREAD

**Issue by NeptuneIX** [mukul500/AnimeXStream#60]
Basically on my tablet(galaxy tab a 10.1 2016) it says "no internet connection" sometimes when i click the button to go to the next video, its not a big problem as closing and opening the video fixes it but its just something to be aware of :) 
My internet is excellent so i can assure you that's not the issue

**Comment by shoukolate** [comment]
Happens on Xiaomi MI A2 as well

**Comment by baskid11** [comment]
Happen

**Comment by baskid11** [comment]
Happens on Android as well but just click retry and everything will be okay.

**Comment by mukul500** [comment]
A new version is out[ Download ](https://github.com/mukul500/AnimeXStream/releases/tag/v0.4.0) .That fixes all issues, Update your app to the latest version
