### ISSUE TITLE
[Bug] Android tv pip and play next

### ISSUE THREAD

**Issue by lamvuong2019** [mukul500/AnimeXStream#62]
I think android tv working is not intended yet, but it is working nevertheless.

Can't seem to get the button to navigate to play next. 

When you press menu it takes you to pip, there is no way to get back to full screen, if you are in a different app.

Testing this on shield tv 2017 firmware 8.0.3

**Comment by mukul500** [comment]
App not ready for Android TV. But in Future, it will be built for TV
