### ISSUE TITLE
[BUG] Android Tv crashes on Search attempt

### ISSUE THREAD

**Issue by mirzasohailbaig** [mukul500/AnimeXStream#63]
I know focus of app may not be android TV at the moment but it works for the most part except for search function which was working in earlier version but not anymore. I'm using shield tv pro 2019 latest firmware and whenever I type a show a name and press enter to search, app crashes. 

Current app version is v. 0.2.1

**Comment by mukul500** [comment]
This app is not ready for Android TV. But in future, there might me update for TV
