### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by baskid11** [mukul500/AnimeXStream#68]
I was watching One Piece yesterday before I went to bed and today I woke up and it isn't playing I tried another movie and it isn't working either.

**Comment by baskid11** [comment]
I don't know if it's just m

**Comment by baskid11** [comment]
I don't know if it's just my mobile.

**Comment by PlatinumBeing** [comment]
Same. I can't watch anything either

**Comment by Civetz0** [comment]
Same for me. It just shows the pause button

**Comment by tsev1000** [comment]
Doesn't work for me either...

**Comment by aramo44** [comment]
this problem is for all users the app not starting video even if u click start button ,guess we need new update 🥰

**Comment by mukul500** [comment]
A new version is out[ Download ](https://github.com/mukul500/AnimeXStream/releases/tag/v0.4.0) .That fixes all issues, Update your app to the latest version
