### ISSUE TITLE
Suggestion Added search by categories

### ISSUE THREAD

**Issue by aramo44** [mukul500/AnimeXStream#69]
I hope we see search by category since the anime list in application showing each anime category ,that we could see an option for searching with custom category to see certain anime list

**Comment by mukul500** [comment]
Please see #76 for app suggestions

**Comment by Colorstips** [comment]
Bro I want your company rocks after making movies and TV series app Hollywood,bollywood,korean,mexican movies tv and all genre anime series and movies app. After making this app.Dude if you makes more cheer for you then you and your company should try far more aswome this app there million's of catagory & genre for that app.I wish if you and your company made that people will extremely superbely Amazing Dude
