### ISSUE TITLE
[BUG] App closes when you press back button while in video

### ISSUE THREAD

**Issue by Hidlsh** [mukul500/AnimeXStream#70]
If you're watching an episode and press the back button on your phone, the app closes and you get an error from Android System: "Anime X Stream has stopped working/Anime X Stream keeps closing". I am not sure if this is a universal problem or just for my phone in particular; [Android Version 7.1.1] [Phone: Z982/ZTE Blade Max Pro] 
![Screenshot_20200630-100814](https://user-images.githubusercontent.com/67646781/86143217-c7154f00-bab9-11ea-817f-a50b653991d6.png)

**Comment by JPBuenaventura** [comment]
Pressing back will play the anime in a PiP window which is natively supported on android 8 and onwards. The thing is some manufacturers, zte included, would port these features down to nougat (android 7) which might cause the problem. A work around is to disable anime x stream's app permission, "display on top of other apps"

**Comment by Hidlsh** [comment]
My ZTE doesn't seem to have such a setting, neither does it show the notification when in/out of the Anime X Stream app (or any other app)

**Comment by mukul500** [comment]
A new version is out[ Download ](https://github.com/mukul500/AnimeXStream/releases/tag/v0.4.0) .That fixes all issues, Update your app to the latest version
