### ISSUE TITLE
[Suggestion] MyAnimeList Sync & Manual Toggles

### ISSUE THREAD

**Issue by ashu-kashyap** [mukul500/AnimeXStream#73]
1. Our progress need to be saved, integrate with either **MyAnimeList** or **make your own cloud** but must include column of; watching, planned to watch & completed.
2. When my phone doesn't have rounded corners why in the app. Pls add **manual toggle** for rounded corners and dark mode.
3. Finnaly brightness and Volume control by swiping down would be great (not necessary but makes life easy)

Thank you very much i love your app :)

#NewFeatures #Fix #Enhancement

**Comment by mukul500** [comment]
1. I would be implementing my own cloud for syncing Favourites. There will be no seperate Watching, Completed etc. Only one Favourite section. 
2. Will add manually Dark mode option
3. This feature is already in my TODO list.

NOTE- GogoAnime have put an authentication system on their videos server. I somehow manged to get videos from their optional server. If they further put authentication on optional server. I don't think i would get videos url. Only option would be enabling Webview with player. But i won't do this & Shut this project

**Comment by justdvnsh** [comment]
@mukul500 I was already workig on feature 2 and 3 . Would be adding a pull request by tonight or tomorrow. !

**Comment by mukul500** [comment]
Oh That would be cool.

**Comment by mukul500** [comment]
Pleas see #76 for Features suggestion
