### ISSUE TITLE
Video Player is Not working

### ISSUE THREAD

**Issue by rafayumair** [mukul500/AnimeXStream#74]
I tried to build my own app with source code. but when I click on any episodes. it's not playing any. it was working 3 days ago. but not now. Original Apk is Working perfectly. Not not mine. Why?. can you give some solutions

**Comment by justdvnsh** [comment]
@mukul500 Did you look at this issue ? I have started to face the same issue. The video player is not working. It starts the video player activity but the streaming does not starts, even after clicking the play button.

**Comment by mukul500** [comment]
I think ur branch is not uptodate with dev branch. So please fetch it. I already had fixed that issue

**Comment by justdvnsh** [comment]
yes. i think that's why the code got repeated in the last pull request.

**Comment by mukul500** [comment]
issues are fixed so closing for now

**Comment by jjarroyo** [comment]
Video Player is Not working source code

**Comment by mukul500** [comment]
@jjarroyo Update ur branch with dev branch. It will work

**Comment by Jafar396** [comment]
How can i uptodate my branch with de branch please help

**Comment by jjarroyo** [comment]
@mukul500 Thank you. copy dev branch and it worked
