### ISSUE TITLE
New episodes appear empty and do not play

### ISSUE THREAD

**Issue by Greeencobra** [mukul500/AnimeXStream#84]
Occasionally, on clicking new episodes that have just come out that day, they appear as a blank video player. (Says length of episode is 0:00, you can't interact with the quality, play button doesn't do anything). I don't know under what circumstances this happens because this week I tried playing some episodes that had just come out that day, and none of them played and even the day after, they still weren't playing, however the week before, the episodes weren't playing and then a few hours later they started working again.

Potential situations that this might happen in are when the app has been left open for a while and then reopened, showing the episode but maybe not actually loading any data. Not sure though, haven't looked into it that much as it hasn't happened too many times yet.

**Comment by Giosel** [comment]
I'm still having the problem

**Comment by Sdark19** [comment]
It happens with most of the newly aired episodes

**Comment by mukul500** [comment]
Check new Release [Download v0.2.3](https://github.com/mukul500/AnimeXStream/releases/tag/v0.2.3)
