### ISSUE TITLE
I dont really know how to use this website 

### ISSUE THREAD

**Issue by Doesntknowhowtouse** [mukul500/AnimeXStream#85]
So how do I update the app I have been trying stuff for a while I'm just trying to update to v0.2.2

**Comment by twiz-ahk** [comment]
https://github.com/mukul500/AnimeXStream/releases

**Comment by GoluLiliput** [comment]
Download the apk from the assets menu u see under a release. Touch 'Assets' and download the .apk which suits your device. Most probably u can use the arm64 version
