### ISSUE TITLE
Permanent Fix for Indian Users of the app

### ISSUE THREAD

**Issue by GoluLiliput** [mukul500/AnimeXStream#89]
As most of might be knowing that many anime sites are blocked in India recently by the government. So the only permanent fix for the app will be of @mukul500 replaces the source gogoanime with https://www.animeseries.io/ .

This source is 100% duplicate of gogoanime with few more resolution options. It's successful implementation would ensure the continuation of the app usage in India. I request the developer, on behalf of every other Indian user to use this replacement source. The added benefit is that this source doesn't try to kick the scrapers out like gogoanime sometimes does so that would clearly ensure better app uptimes than ever before for all global users alike.

**Comment by shrey-kapoor** [comment]
Yeah the app is not working.
![Screenshot_20200808-003800_Anime X Stream](https://user-images.githubusercontent.com/69365989/89679805-73dfb900-d90f-11ea-8afd-185f801d33df.jpg)

**Comment by yash1441** [comment]
Or just use VPN...

**Comment by mukul500** [comment]
Please Check Latest Release [v0.2.4](https://github.com/mukul500/AnimeXStream)
