### ISSUE TITLE
There a server issue

### ISSUE THREAD

**Issue by usesgithub** [mukul500/AnimeXStream#93]
Anything I try to watch says server issue

**Comment by GoluLiliput** [comment]
R u on discord? If yes give me the username. I will help u out. If not, gimme email.

**Comment by CAESAR5769** [comment]
Pls give discord link

**Comment by zeeshanhussain** [comment]
Use https://transfer.sh/bh9ob/AnimexStream-v0.2.1-arm64-v8a-release.apk until its fixed in the current repo.

**Comment by mukul500** [comment]
Check new Release [Download v0.2.3](https://github.com/mukul500/AnimeXStream/releases/tag/v0.2.3)
