### ISSUE TITLE
Server Error

### ISSUE THREAD

**Issue by CharaVs** [mukul500/AnimeXStream#94]
Ever since today,  I've tried to watch the anime I usually
watch but this time it kept saying "server error"

**Comment by GoluLiliput** [comment]
That's because... India has banned gogoanime. 
Use AnimeZone instead. Join their discord server and ur issue will b fixed immediately if any

**Comment by avxbrm** [comment]
What is animeZone??

**Comment by GoluLiliput** [comment]
It's an anime app for Android, listed in the official AnimePiracy Community

**Comment by zeeshanhussain** [comment]
Use https://transfer.sh/bh9ob/AnimexStream-v0.2.1-arm64-v8a-release.apk until its fixed in the current repo.

**Comment by mukul500** [comment]
Check new Release [Download v0.2.3](https://github.com/mukul500/AnimeXStream/releases/tag/v0.2.3)
