### ISSUE TITLE
Server error pls solve it 

### ISSUE THREAD

**Issue by SHADow5446** [mukul500/AnimeXStream#95]
![Screenshot_2020-08-15-12-46-15-972_net xblacky animexstream](https://user-images.githubusercontent.com/69710401/90307601-573a1700-def5-11ea-807f-f19726b8a4a6.jpg)

**Comment by GoluLiliput** [comment]
Use AnimeZone.

**Comment by Civetz0** [comment]
It's okay now

**Comment by avxbrm** [comment]
> Use AnimeZone.

What is that??

**Comment by GoluLiliput** [comment]
It's an anime app

**Comment by avxbrm** [comment]
Where can i download that didn't get in Google :_:

**Comment by GoluLiliput** [comment]
Google in AnimeZone Github

**Comment by GoluLiliput** [comment]
> Where can i download that didn't get in Google :_:

R u on discord?

**Comment by avxbrm** [comment]
Got it from github🔥 and thanks for help❣️

**Comment by GoluLiliput** [comment]
No problem. Join their discord server to report a y bug and issues. The dev will directly contact u and make sure the bug is fixed. The dev is very active there too.

**Comment by zeeshanhussain** [comment]
Use https://transfer.sh/bh9ob/AnimexStream-v0.2.1-arm64-v8a-release.apk until its fixed in the current repo.

**Comment by mukul500** [comment]
Check new Release [Download v0.2.3](https://github.com/mukul500/AnimeXStream/releases/tag/v0.2.3)
