### ISSUE TITLE
Please Solve the server Issue 

### ISSUE THREAD

**Issue by JainKrish008** [mukul500/AnimeXStream#96]
Fix your server problem

**Comment by Civetz0** [comment]
True

**Comment by zeeshanhussain** [comment]
Use https://transfer.sh/bh9ob/AnimexStream-v0.2.1-arm64-v8a-release.apk until its fixed in the current repo.

**Comment by mukul500** [comment]
Check new Release [Download v0.2.3](https://github.com/mukul500/AnimeXStream/releases/tag/v0.2.3)
