### ISSUE TITLE
Unactive disconnect from sever

### ISSUE THREAD

**Issue by Jafar396** [mukul500/AnimeXStream#97]
When I download your app and build it and open the episode show me "unactive disconnect from the server" in run dailog in android studio

**Comment by zeeshanhussain** [comment]
Use https://transfer.sh/bh9ob/AnimexStream-v0.2.1-arm64-v8a-release.apk until its fixed in the current repo.

**Comment by mukul500** [comment]
Check new Release [Download v0.2.3](https://github.com/mukul500/AnimeXStream/releases/tag/v0.2.3)
