### ISSUE TITLE
Server Error

### ISSUE THREAD

**Issue by JengleSnaps** [mukul500/AnimeXStream#99]
Whenever I hop onto the app and start to watch my shows it just says server error and I can't do anything about it. If you are using kissanime.ru it was recently taken down.

**Comment by zeeshanhussain** [comment]
Use https://transfer.sh/bh9ob/AnimexStream-v0.2.1-arm64-v8a-release.apk until its fixed in the current repo.

**Comment by mukul500** [comment]
Check new Release [Download v0.2.3](https://github.com/mukul500/AnimeXStream/releases/tag/v0.2.3)
